#!/usr/bin/env bash
#
# Default setup script
# Setup the directory server for the cts backend.

# This uses DS setup profiles. If the schema for a profile has not been
# changed it may use an older version. For example, AM CTS 7.5 still uses the 6.5 schema for configuration
AM_CTS="am-cts:6.5"
DS_PROXIED_SERVER="ds-proxied-server:7.1"

setup-profile --profile ${AM_CTS} \
              --set am-cts/tokenExpirationPolicy:am-sessions-only \
              --set am-cts/amCtsAdminPassword:password \
 && setup-profile --profile ${DS_PROXIED_SERVER} \
                  --set ds-proxied-server/proxyUserDn:uid=proxy \
                  --set ds-proxied-server/proxyUserCertificateSubjectDn:CN=ds,O=ForgeRock.com

# Copy custom schema files into db after setup-profiles have been imported
cp -a /opt/opendj/custom-schema/*.ldif /opt/opendj/data/db/schema
rm -rf /opt/opendj/custom-schema

# The default in 7.x is to use PBKDF2 password hashing - which is many order of magnitude slower than
# SHA-512. We recommend leaving PBKDF2 as the default as it more secure.
# If you wish to revert to the less secure SHA-512, Uncomment these lines:
#dsconfig --offline --no-prompt --batch <<EOF
##    set-password-storage-scheme-prop --scheme-name "Salted SHA-512" --set enabled:true
##    set-password-policy-prop --policy-name "Default Password Policy" --set default-password-storage-scheme:"Salted SHA-512"
#EOF


echo "Done."