# Image passed pit1 test phase
FROM gcr.io/forgerock-io/ig/pit1:7.0.0-latest-postcommit

# Copy all config files into the docker image.
#COPY --chown=forgerock ./ /config
COPY --chown=forgerock ./ /var/openig
