{
 "title": "AM 8.0.1 CTS",
 "tags": [
  "AM",
  "Prometheus",
  "8.0.1"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(am_cts_task_seconds,job)"
    }
   },
   { "name": "aggregation_window", "label": "Aggregation Window", "query": "1m,5m,15m,1h,1d" },
   {
    "name": "token_type",
    "label": "Token Type",
    "query": {
     "query": "label_values(am_cts_task_seconds, token_type)"
    }
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": {
     "query": "label_values(am_cts_task_seconds, operation)"
    }
   },
   {
    "name": "quantile",
    "label": "Percentile",
    "query": {
     "query": "label_values(am_cts_task_seconds, quantile)"
    }
   },
   { "name": "outcome", "label": "Outcome", "query": "success,failure" }
  ]
 },
 "panels": [
  {
   "title": "CTS Cluster Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total Tasks Throughput [$aggregation_window]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(am_cts_task_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Overall Average Task Service Time [$aggregation_window]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(am_cts_task_seconds_total{job=~\"$instance\"}[$aggregation_window])) / sum (rate(am_cts_task_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Pending Operations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "op" } },
   "yaxes": [
    { "format": "op" }
   ],
   "targets": [
    { "expr": "am_cts_task_pending", "legendFormat": "{{operation}}" }
   ]
  },
  {
   "title": "Average Task Service Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(am_cts_task_seconds_total{job=~\"$instance\"}[90s])) / sum by (job) (rate(am_cts_task_count{job=~\"$instance\"}[90s]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Connection Pools",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 9 },
   "targets": [
    { "expr": "am_cts_connection_state", "legendFormat": "{{status}}" }
   ]
  },
  {
   "title": "Connection Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connections Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(am_cts_connection_count{job=~\"$instance\",outcome=~\"$outcome\"}[5m])",
     "legendFormat": "{{job}} {{outcome}}"
    }
   ]
  },
  {
   "title": "Connections Service Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "am_cts_connection_seconds{quantile=\"0.5\"}",
     "legendFormat": "{{job}} {{outcome}}"
    }
   ]
  },
  {
   "title": "$operation Tasks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "repeat": "operation",
   "targets": [
    {}
   ]
  },
  {
   "title": "$operation Task Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(am_cts_task_count{job=~\"$instance\",token_type=~\"$token_type\",operation=~\"$operation\",outcome=~\"$outcome\"}[5m])",
     "legendFormat": "{{job}} {{token_type}} {{outcome}}"
    }
   ]
  },
  {
   "title": "$operation Task Service Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "am_cts_task_seconds{job=~\"$instance\",token_type=~\"$token_type\",operation=~\"$operation\",quantile=~\"$quantile\",outcome=~\"$outcome\"}",
     "legendFormat": "{{job}} {{token_type}} {{outcome}} p{{quantile}}"
    }
   ]
  }
 ]
}