{
 "title": "Wajih IDC Vitals",
 "time": { "from": "2025-01-31T05:34:05.013Z", "to": "2025-01-31T06:41:18.047Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(ds_health_status_healthy{cluster=\"$cluster\"},pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Entry Count - $instance",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (base_dn) (ds_backend_entry_count{cluster=\"$cluster\",pod=\"$instance\"})",
     "legendFormat": "# entries"
    }
   ]
  },
  {
   "title": "haproxy_backend_response_time_average_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (cluster, proxy) (haproxy_backend_response_time_average_seconds{cluster=\"$cluster\"})",
     "legendFormat": "{{proxy}}"
    }
   ]
  },
  {
   "title": "vCPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sort_desc(sum by(container, instance) (rate(container_cpu_usage_seconds_total{cluster=\"$cluster\", namespace=~\"(fr-platform|org-public)\",container!=\"\"}[$__rate_interval]))) > 0.001",
     "legendFormat": "{{instance}}_{{container}}"
    }
   ]
  },
  {
   "title": "container_cpu_cfs_throttled_seconds_total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(container,instance) (rate(container_cpu_cfs_throttled_seconds_total{cluster=\"$cluster\",namespace=\"fr-platform\"}[$__rate_interval]))",
     "legendFormat": "{{instance}}_{{container}}"
    },
    {
     "expr": "sum by(container,instance) (rate(container_cpu_cfs_throttled_seconds_total{cluster=\"$cluster\",namespace=\"org-public\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Disk Busy Percentage",
   "type": "timeseries",
   "description": "https://brooker.co.za/blog/2014/07/04/iostat-pct.html",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{cluster=\"$cluster\"}[1m]) * 100",
     "legendFormat": "{{node}} - {{device}}"
    }
   ]
  },
  {
   "title": "HAProxy Frontend Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(haproxy_frontend_http_requests_total{cluster=\"$cluster\", app=\"haproxy\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum(pod:cpu_usage_mcpu:sum{cluster=\"$cluster\"}) by (kube_node_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "haproxy_backend_response_time_average_seconds for last 1024 connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod, proxy) (haproxy_backend_response_time_average_seconds{cluster=\"$cluster\",proxy=~\"be_(am|am_internal|idm)\"})",
     "legendFormat": "{{pod}}/{{proxy}}"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(\n    ds_replication_replica_remote_replicas_replay_delay_seconds{\n        cluster=\"$cluster\",pod=\"userstore-0\",remote_server_id=\"userstore-1\", domain_name=\"ou=identities\"})",
     "legendFormat": "repl1->repl0"
    },
    {
     "expr": "max(\n    ds_replication_replica_remote_replicas_replay_delay_seconds{\n        cluster=\"$cluster\",pod=\"userstore-0\",remote_server_id=\"userstore-2\", domain_name=\"ou=identities\"})",
     "legendFormat": "repl2->repl0"
    },
    {
     "expr": "max(\n    ds_replication_replica_remote_replicas_replay_delay_seconds{\n        cluster=\"$cluster\",pod=\"userstore-1\",remote_server_id=\"userstore-0\", domain_name=\"ou=identities\"})",
     "legendFormat": "repl0->repl1"
    },
    {
     "expr": "max(\n    ds_replication_replica_remote_replicas_replay_delay_seconds{\n        cluster=\"$cluster\",pod=\"userstore-1\",remote_server_id=\"userstore-2\", domain_name=\"ou=identities\"})",
     "legendFormat": "repl2->repl1"
    },
    {
     "expr": "max(\n    ds_replication_replica_remote_replicas_replay_delay_seconds{\n        cluster=\"$cluster\",pod=\"userstore-2\",remote_server_id=\"userstore-0\", domain_name=\"ou=identities\"})",
     "legendFormat": "repl0->repl2"
    },
    {
     "expr": "max(\n    ds_replication_replica_remote_replicas_replay_delay_seconds{\n        cluster=\"$cluster\",pod=\"userstore-2\",remote_server_id=\"userstore-1\", domain_name=\"ou=identities\"})",
     "legendFormat": "repl1->repl2"
    },
    {
     "expr": "max(\n    ds_replication_replica_remote_replicas_replay_delay_seconds{\n        cluster=\"$cluster\",pod=\"ctsstore-0\",remote_server_id=\"ctsstore-1\", domain_name=\"ou=tokens\"})",
     "legendFormat": "CTS: repl0->repl1"
    },
    {
     "expr": "max(\n    ds_replication_replica_remote_replicas_replay_delay_seconds{\n        cluster=\"$cluster\",pod=\"ctsstore-1\",remote_server_id=\"ctsstore-0\", domain_name=\"ou=tokens\"})",
     "legendFormat": "CTS: repl1->repl0"
    }
   ]
  },
  { "title": "DS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CTS Pending Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "op" } },
   "targets": [
    {
     "expr": "am_cts_task_pending{cluster=\"$cluster\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Avg Etime Per Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (pod,scope) (rate(ds_connection_handlers_ldap_requests_seconds_total{cluster=\"$cluster\",ldap_handler=\"LDAP\",type=\"search\",app=\"userstore\"}[$__rate_interval])/rate(ds_connection_handlers_ldap_requests_count{cluster=\"$cluster\",ldap_handler=\"LDAP\",type=\"search\",app=\"userstore\"}[$__rate_interval])*1000)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (pod,scope) (rate(ds_connection_handlers_ldap_requests_seconds_total{cluster=\"$cluster\",ldap_handler=\"LDAP\",type=\"search\",app=\"ctsstore\"}[$__rate_interval])/rate(ds_connection_handlers_ldap_requests_count{cluster=\"$cluster\",ldap_handler=\"LDAP\",type=\"search\",app=\"ctsstore\"}[$__rate_interval])*1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AM CTS Reaper Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "am_cts_reaper_cache_size{cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}",
     "target": "aliasByNode($host.$instance.cts.reaper.cache.size, 5)"
    }
   ]
  },
  {
   "title": "DS TTL-based Deletion Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(ds_backend_ttl_entries_deleted_count{cluster=\"$cluster\",app=\"ctsstore\"}[$__rate_interval])",
     "legendFormat": "{{pod}}",
     "target": "aliasByNode(perSecond($host.$instance.cts.reaper.cache.*.deletion.$outcome.count), 5)"
    }
   ]
  },
  {
   "title": "Avg Etime Per Transaction ctsstore",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by (pod,scope) (rate(ds_connection_handlers_ldap_requests_seconds_total{cluster=\"$cluster\",ldap_handler=\"LDAP\",app=\"ctsstore\"}[$__rate_interval])/rate(ds_connection_handlers_ldap_requests_count{cluster=\"$cluster\",ldap_handler=\"LDAP\",app=\"ctsstore\"}[$__rate_interval])*1000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DS Worker Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "ds_work_queue_requests_in_queue{cluster=\"$cluster\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "DS container_memory_used %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "targets": [
    {
     "expr": "round(100 * sum(container_memory_working_set_bytes{cluster=\"$cluster\",namespace=\"fr-platform\",container=\"ds\"}) by (pod) /\nsum(container_spec_memory_limit_bytes{cluster=\"$cluster\",namespace=\"fr-platform\",container=\"ds\"}) by (pod))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DS Disk IOPS",
   "type": "timeseries",
   "description": "Writes are inverted values (negative Y axis)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_total{cluster=\"$cluster\",container=\"ds\",instance=\"$instance\"}[5m])) by (device)",
     "legendFormat": "reads {{device}}"
    },
    {
     "expr": "sum(rate(container_fs_writes_total{cluster=\"$cluster\",container=\"ds\",instance=\"$instance\"}[5m])) by (device)",
     "legendFormat": "writes {{device}}"
    }
   ]
  },
  {
   "title": "DS Entry Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum by (backend) (\n   ds_backend_entry_count{\n      cluster=\"$cluster\",\n      backend=~\"amIdentityStore|amCts\"\n   }\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (backend) (\n   ds_backend_entry_count{\n      cluster=\"$cluster\",\n      backend=\"amCts\"\n   }\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DS Disk throughput",
   "type": "timeseries",
   "description": "Writes are inverted values (negative Y axis)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(container_fs_reads_bytes_total{cluster=\"$cluster\",container=\"ds\",instance=\"$instance\"}[5m])) by (device)",
     "legendFormat": "reads {{device}}"
    },
    {
     "expr": "sum(rate(container_fs_writes_bytes_total{cluster=\"$cluster\",container=\"ds\",instance=\"$instance\"}[5m])) by (device)",
     "legendFormat": "writes {{device}}"
    }
   ]
  },
  {
   "title": "DS Backend Entry Counts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\n   ds_backend_entry_count{\n      cluster=\"$cluster\",\n      base_dn=~\"ou=identities|dc=openidm,dc=example,dc=com|ou=tokens\"\n   }\n",
     "legendFormat": "{{base_dn}}_{{pod}}"
    }
   ]
  },
  {
   "title": "DS Entry Creation Rate > 0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(ds_backend_entry_count{cluster=\"$cluster\",container=\"ds\"}[$__rate_interval]) > 0",
     "legendFormat": "{{base_dn}}"
    }
   ]
  },
  {
   "title": "Total  $instance Write Operations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "rate(\n    ds_connection_handlers_ldap_requests_count{\n        cluster=\"$cluster\",\n        instance=\"$instance\",\n        ldap_handler=\"LDAP\",\n        type=\"delete\"\n    }[$__rate_interval]\n)",
     "legendFormat": "{{pod}} - Delete"
    },
    {
     "expr": "rate(\n    ds_connection_handlers_ldap_requests_count{\n        cluster=\"$cluster\",\n        instance=\"$instance\",\n        ldap_handler=\"LDAP\",\n        type=\"add\"\n    }[$__rate_interval]\n)",
     "legendFormat": "{{pod}} - Add"
    },
    {
     "expr": "rate(\n    ds_connection_handlers_ldap_requests_count{\n        cluster=\"$cluster\",\n        instance=\"$instance\",\n        ldap_handler=\"LDAP\",\n        type=\"modify\"\n    }[$__rate_interval]\n)",
     "legendFormat": "{{pod}} - Modify"
    },
    {
     "expr": "sum(rate(\n    ds_connection_handlers_ldap_requests_count{\n        cluster=\"$cluster\",\n        instance=\"$instance\",\n        ldap_handler=\"LDAP\",\n        type=~\"modify|add|delete\"\n    }[$__rate_interval]\n))",
     "legendFormat": "{{pod}} - Total Writes"
    }
   ]
  },
  {
   "title": "DS $instance Response Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "rate(\n    ds_connection_handlers_ldap_requests_seconds_total{\n        cluster=\"$cluster\",\n        pod=\"$instance\",\n        ldap_handler=\"LDAP\",\n        type=\"add\"\n    }[$__rate_interval]\n)/\nrate(\n    ds_connection_handlers_ldap_requests_count{\n        cluster=\"$cluster\",\n        instance=\"$instance\",\n        ldap_handler=\"LDAP\",\n        type=\"add\"\n    }[$__rate_interval]\n)*1000",
     "legendFormat": "{{pod}} - Add"
    },
    {
     "expr": "rate(\n    ds_connection_handlers_ldap_requests_seconds_total{\n        cluster=\"$cluster\",\n        pod=\"$instance\",\n        ldap_handler=\"LDAP\",\n        type=\"delete\"\n    }[$__rate_interval]\n)/\nrate(\n    ds_connection_handlers_ldap_requests_count{\n        cluster=\"$cluster\",\n        instance=\"$instance\",\n        ldap_handler=\"LDAP\",\n        type=\"delete\"\n    }[$__rate_interval]\n)*1000",
     "legendFormat": "{{pod}} - Delete"
    },
    {
     "expr": "rate(\n    ds_connection_handlers_ldap_requests_seconds_total{\n        cluster=\"$cluster\",\n        pod=\"$instance\",\n        ldap_handler=\"LDAP\",\n        type=\"modify\"\n    }[$__rate_interval]\n)/\nrate(\n    ds_connection_handlers_ldap_requests_count{\n        cluster=\"$cluster\",\n        instance=\"$instance\",\n        ldap_handler=\"LDAP\",\n        type=\"modify\"\n    }[$__rate_interval]\n)*1000",
     "legendFormat": "{{pod}} - Modify"
    }
   ]
  },
  { "title": "AM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 98 } },
  {
   "title": "AM - Memory Used",
   "type": "timeseries",
   "description": "Memory Requested refers to the memory guaranteed to this workload (memory_requests) - Limits will be greyed if they are not configured",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(max_over_time(container_memory_working_set_bytes{cluster=\"$cluster\",container=\"openam\"}[1h]))",
     "legendFormat": "Max Memory Used"
    },
    {
     "expr": "avg(avg_over_time(container_memory_working_set_bytes{cluster=\"$cluster\",container=\"openam\"}[15m]))",
     "legendFormat": "Avg Memory Used"
    },
    {
     "expr": "min(min_over_time(container_memory_working_set_bytes{cluster=\"$cluster\",container=\"openam\"}[1h]))",
     "legendFormat": "Min Memory Used"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\",container=\"openam\"}) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "max(max_over_time(kube_pod_container_resource_limits{cluster=\"$cluster\",container=\"openam\",resource=\"memory\",unit=\"byte\"}[15m]))",
     "legendFormat": "Memory Limit"
    },
    {
     "expr": "max(max_over_time(kube_pod_container_resource_requests{cluster=\"$cluster\",container=\"openam\",resource=\"memory\",unit=\"byte\"}[15m]))",
     "legendFormat": "Memory Requested"
    },
    {
     "expr": "max(am_jvm_memory_usage_heap_max{cluster=\"$cluster\",container=\"openam\"})",
     "legendFormat": "Heap Limit"
    },
    {
     "expr": "max(am_jvm_memory_usage_non_heap_max{cluster=\"$cluster\",container=\"openam\"})",
     "legendFormat": "Non-Heap Limit"
    }
   ]
  },
  {
   "title": "Successful AuthN Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "irate(am_authentication_count{cluster=\"$cluster\"}[1m])",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "AM JVM Max Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 107 },
   "targets": [
    {
     "expr": "am_jvm_memory_usage_heap_max{cluster=\"$cluster\", namespace=\"fr-platform\"} ",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Session Creation Success/Failure Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 107 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by (cluster,outcome) (\nirate(am_session_count{cluster=\"$cluster\",session_type=~\"client-based|cts-based\",outcome=\"success\",operation=~\"create\"}[1m])\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by (cluster,outcome) (\n  irate(am_authentication_count{cluster=\"$cluster\",outcome=\"failure\"}[1m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AM Used Threadpools > 0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 115 },
   "targets": [
    {
     "expr": "sum by(pod, context) (am_scripting_threadpool_threads_count{cluster=\"$cluster\"}) > 0",
     "legendFormat": "{{pod}} {{context}}"
    }
   ]
  },
  {
   "title": "am_jvm_thread_state_blocked_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 115 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(am_jvm_thread_state_blocked_count{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "am_scripting_threadpool_threads_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 123 },
   "targets": [
    {
     "expr": "sum by(pod) (am_scripting_threadpool_threads_count{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AM Sessions per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 123 },
   "targets": [
    {
     "expr": "avg(am_session_seconds{cluster=\"$cluster\", outcome=\"success\", operation=\"create\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AM Scripting Threads (blocked)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 131 },
   "targets": [
    {
     "expr": "am_scripting_threadpool_threads_count{cluster=\"$cluster\",namespace=\"fr-platform\",state=\"blocked\"}",
     "legendFormat": "{{pod}} - blocked"
    }
   ]
  },
  {
   "title": "AM JVM Threads",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 131 },
   "targets": [
    {
     "expr": "am_jvm_thread_state_count{cluster=\"$cluster\", namespace=\"fr-platform\"} ",
     "legendFormat": "{{pod}} - count"
    },
    {
     "expr": "am_jvm_thread_state_blocked_count{cluster=\"$cluster\", namespace=\"fr-platform\"}",
     "legendFormat": "{{pod}} - blocked"
    },
    {
     "expr": "am_jvm_thread_state_timed_waiting_count {cluster=\"$cluster\", namespace=\"fr-platform\"}",
     "legendFormat": "{{pod}} - waiting"
    }
   ]
  },
  {
   "title": "AM CTS Task Count > 0",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 142 },
   "targets": [
    {
     "expr": "sum(rate(am_cts_task_count{cluster=\"${cluster}\",job=~\"k8s-sd-am-metrics\",token_type=~\"(authentication-whitelist|back-channel-authentication-state|cluster-notification|logout-user|oauth2|oauth2-blacklist|oauth2-csrf-protection|oauth2-grant-set|oauth2-stateless|oauth2-stateless-grant|push-notification|request-uri-object|resource-set|rest|saml2|session|session-blacklist|sts|suspended-auth-session|transaction|unknown)\",operation=~\"create\",outcome=~\"(success|failure)\"}[2m])) by (pod,token_type,operation,outcome) > 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(rate(am_oauth2_grant_count{cluster=\"${cluster}\", grant_type=~\".*\"}[2m])) by (pod,grant_type) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "am_authorization_policy_set_evaluate_seconds",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 142 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (quantile) (am_authorization_policy_set_evaluate_seconds{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "am_cts_connection_state",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "targets": [
    {
     "expr": "sum by (status) (am_cts_connection_state{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AM Blacklist Search",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "targets": [
    {
     "expr": "am_blacklist_cts_search_seconds{cluster=\"$cluster\",quantile=\"0.99\"}",
     "legendFormat": "{{pod}} - {{blacklist_type}}  - {{outcome}}"
    }
   ]
  },
  { "title": "IDM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 } },
  {
   "title": "IDM Relationships",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 159 },
   "targets": [
    {
     "expr": "identities_total{cluster=\"$cluster\", container=\"mon-identities-exporter\", identitytype=\"relationships\", realm=\"alpha\"}",
     "legendFormat": "identities_total"
    },
    {
     "expr": "sum by(index) (elasticsearch_indices_shards_docs{cluster=\"$cluster\",index=\"${cluster}_openidm_relationship_latest\"})",
     "legendFormat": "{{index}}"
    },
    {
     "expr": "sum(idm_virtualpropertiesfromrelationships_count{cluster=\"$cluster\"})",
     "legendFormat": "idm_virtualpropertiesfromrelationships_count"
    }
   ]
  },
  {
   "title": "IDM Managed User Object",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 159 },
   "targets": [
    {
     "expr": "idm_managed_seconds{cluster=\"$cluster\", managed_object=~\".*user.*\", operation=~\"(create|patch|update)\"}",
     "legendFormat": "{{pod}} - {{operation}}"
    },
    {
     "expr": "sum(idm_managed_seconds{cluster=\"$cluster\", managed_object=~\".*user.*\", quantile=\"0.5\", operation=~\"(create|patch|update)\"})",
     "legendFormat": "sum"
    }
   ]
  },
  {
   "title": "IDM Managed Operations (seconds) P99",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 167 },
   "targets": [
    {
     "expr": "idm_managed_seconds{cluster=~\"$cluster\", managed_object=~\".*user.*\", operation=~\"(create|patch|update)\", managed_object=~\"(alpha_user|alpha_usermeta)\", quantile=\"0.99\"}",
     "legendFormat": "{{managed_object}} - {{operation}}"
    },
    {}
   ]
  },
  {
   "title": "IDM Queued Sync",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 167 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(pod) (sync_queue_total{cluster=\"$cluster\", app=\"mon-identities-exporter\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "idm_icf_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 175 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(connector) (rate(idm_icf_seconds{cluster=\"$cluster\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IDM Roles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 175 },
   "targets": [
    {
     "expr": "avg by (realm) (identities_total{cluster=\"$cluster\", container=\"mon-identities-exporter\", identitytype=\"roles\", realm=\"alpha\"})",
     "legendFormat": "{{realm}}"
    },
    {
     "expr": "sum by(index) (elasticsearch_indices_shards_docs{cluster=\"$cluster\",index=\"${cluster}_openidm_internal_role_latest\"})",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Webhook times seconds (quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 183 },
   "targets": [
    {
     "expr": "idm_managed_seconds{managed_object=\"alpha_user\", script=\"postUpdate\", cluster=\"$cluster\", quantile=\"0.99\"}",
     "legendFormat": "{{pod}} - {{script}}"
    }
   ]
  },
  {
   "title": "Webhook times seconds (quantile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 183 },
   "targets": [
    {
     "expr": "idm_managed_seconds{managed_object=\"alpha_user\", script=\"postCreate\", cluster=\"$cluster\"}",
     "legendFormat": "{{pod}} - {{script}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 191 } },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 192 },
   "targets": [
    {
     "expr": "sum(xrate(container_fs_reads_bytes_total{cluster=\"$cluster\",container=\"ds\",instance=~\"ctsstore.*\"}[$__rate_interval])) by (instance, device) / 1048576",
     "legendFormat": "Throughput Read MiB {{instance}}/{{device}}"
    },
    {
     "expr": "sum(xrate(container_fs_reads_total{cluster=\"$cluster\",container=\"ds\",instance=~\"ctsstore.*\"}[$__rate_interval])) by (instance, device)",
     "legendFormat": "IOPS Read {{instance}}/{{device}}"
    },
    {
     "expr": "sum(xrate(container_fs_writes_bytes_total{cluster=\"$cluster\",container=\"ds\",instance=~\"ctsstore.*\"}[$__rate_interval])) by (instance, device) / 1048576",
     "legendFormat": "Throughput Writes MiB {{instance}}/{{device}}"
    },
    {
     "expr": "sum(xrate(container_fs_writes_total{cluster=\"$cluster\",container=\"ds\",instance=~\"ctsstore.*\"}[$__rate_interval])) by (instance, device)",
     "legendFormat": "IOPS Writes {{instance}}/{{device}}"
    }
   ]
  },
  {
   "title": "DS CTS TTL Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 192 },
   "targets": [
    {
     "expr": "ds_backend_ttl_entries_deleted_count{cluster=\"$cluster\", container=\"ds\", app=\"ctsstore\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IGA",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 200 },
   "collapsed": true
  }
 ]
}