#!/usr/bin/env bash
# Adds extra schema on new and existing deployments

set -e

ver=$(dsconfig -V | awk '{ print $1 }')
IDM_REPO_VER=${ver%.*}

# Returns 0 if v1 > v2 (major.minor comparison)
version_gt() {
    awk -v v1="$1" -v v2="$2" 'BEGIN { split(v1,a,"."); split(v2,b,"."); exit !(a[1]>b[1] || (a[1]==b[1] && a[2]>b[2])) }'
}

plug_exists() {
    dsconfig --offline --no-prompt -s list-plugins | grep "^${1}" > /dev/null 2>&1
    return $?
}

PLUG_NAME="User Unique Attribute"
if  plug_exists "$PLUG_NAME" ; then
    echo "Found $PLUG_NAME, skipping create"
else
    echo "Adding '${PLUG_NAME}'"
    dsconfig --offline --no-prompt --batch <<EOF
create-plugin \
        --plugin-name "${PLUG_NAME}" \
        --type "unique-attribute" \
        --set "type:uid" \
        --set "base-dn:ou=people,ou=identities" \
        --set "enabled:true"
EOF
fi

# The plug for unique-attribute of application name requires IDM repo version > 8.0.
if version_gt "$IDM_REPO_VER" "8.0"; then
    PLUG_NAME="Application Name Unique Attribute"
    if plug_exists "$PLUG_NAME" ; then
        echo "Found $PLUG_NAME, skipping create"
    else
        echo "Adding '${PLUG_NAME}'"
        dsconfig --offline --no-prompt --batch <<EOF
create-plugin \
        --plugin-name "${PLUG_NAME}" \
        --type "unique-attribute" \
        --set "type:fr-idm-managed-application-name" \
        --set "base-dn:ou=application,ou=managed,dc=openidm,dc=forgerock,dc=io" \
        --set "enabled:true"
EOF
    fi
fi
