#!/bin/bash

terraform_dir=$(dirname $0)
terraform_bin=$(type -p terraform)
if [ -z "$terraform_bin" ]; then
    echo "Could not find terraform binary in PATH.  Exiting."
    exit 1
fi
terraform="$terraform_bin -chdir=$terraform_dir"

set -e
$terraform init -upgrade
$terraform apply -target=local_file.clusters -auto-approve -compact-warnings $*
$terraform init -upgrade
$terraform apply $*

