// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pubsub "cloud.google.com/go/pubsub"
)

// CallbackHandler is an autogenerated mock type for the CallbackHandler type
type CallbackHandler struct {
	mock.Mock
}

// Callback provides a mock function with given fields: ctx, msg
func (_m *CallbackHandler) Callback(ctx context.Context, msg *pubsub.Message) {
	_m.Called(ctx, msg)
}
