// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pubsub "cloud.google.com/go/pubsub"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *Client) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateSubscription provides a mock function with given fields: _a0, _a1, _a2
func (_m *Client) CreateSubscription(_a0 context.Context, _a1 string, _a2 pubsub.SubscriptionConfig) (*pubsub.Subscription, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *pubsub.Subscription
	if rf, ok := ret.Get(0).(func(context.Context, string, pubsub.SubscriptionConfig) *pubsub.Subscription); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pubsub.Subscription)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, pubsub.SubscriptionConfig) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateTopic provides a mock function with given fields: _a0, _a1
func (_m *Client) CreateTopic(_a0 context.Context, _a1 string) (*pubsub.Topic, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pubsub.Topic
	if rf, ok := ret.Get(0).(func(context.Context, string) *pubsub.Topic); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pubsub.Topic)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Subscription provides a mock function with given fields: _a0
func (_m *Client) Subscription(_a0 string) *pubsub.Subscription {
	ret := _m.Called(_a0)

	var r0 *pubsub.Subscription
	if rf, ok := ret.Get(0).(func(string) *pubsub.Subscription); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pubsub.Subscription)
		}
	}

	return r0
}

// Topic provides a mock function with given fields: id
func (_m *Client) Topic(id string) *pubsub.Topic {
	ret := _m.Called(id)

	var r0 *pubsub.Topic
	if rf, ok := ret.Get(0).(func(string) *pubsub.Topic); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pubsub.Topic)
		}
	}

	return r0
}
