// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	pubsub "cloud.google.com/go/pubsub"
	mock "github.com/stretchr/testify/mock"
)

// MessageServicer is an autogenerated mock type for the MessageServicer type
type MessageServicer struct {
	mock.Mock
}

// Ack provides a mock function with given fields: _a0
func (_m *MessageServicer) Ack(_a0 *pubsub.Message) {
	_m.Called(_a0)
}

// Nack provides a mock function with given fields: _a0
func (_m *MessageServicer) Nack(_a0 *pubsub.Message) {
	_m.Called(_a0)
}
