// Code generated by mockery v1.0.0. DO NOT EDIT.
package mocks

import mock "github.com/stretchr/testify/mock"
import pubsub "cloud.google.com/go/pubsub"

// Nacker is an autogenerated mock type for the Nacker type
type Nacker struct {
	mock.Mock
}

// Nack provides a mock function with given fields: _a0
func (_m *Nacker) Nack(_a0 *pubsub.Message) {
	_m.Called(_a0)
}
