// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ShutdownLifecycle is an autogenerated mock type for the ShutdownLifecycle type
type ShutdownLifecycle struct {
	mock.Mock
}

// Done provides a mock function with given fields: _a0
func (_m *ShutdownLifecycle) Done(_a0 string) {
	_m.Called(_a0)
}

// Register provides a mock function with given fields: _a0
func (_m *ShutdownLifecycle) Register(_a0 string) {
	_m.Called(_a0)
}

// ShuttingDown provides a mock function with given fields:
func (_m *ShutdownLifecycle) ShuttingDown() <-chan struct{} {
	ret := _m.Called()

	var r0 <-chan struct{}
	if rf, ok := ret.Get(0).(func() <-chan struct{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}

	return r0
}
