// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	pubsub "cloud.google.com/go/pubsub"
	mock "github.com/stretchr/testify/mock"
)

// SubscriptionGetter is an autogenerated mock type for the SubscriptionGetter type
type SubscriptionGetter struct {
	mock.Mock
}

// Subscription provides a mock function with given fields: _a0
func (_m *SubscriptionGetter) Subscription(_a0 string) *pubsub.Subscription {
	ret := _m.Called(_a0)

	var r0 *pubsub.Subscription
	if rf, ok := ret.Get(0).(func(string) *pubsub.Subscription); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pubsub.Subscription)
		}
	}

	return r0
}
