// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	sync "sync"
)

// SubscriptionServicer is an autogenerated mock type for the SubscriptionServicer type
type SubscriptionServicer struct {
	mock.Mock
}

// ReceiveMessages provides a mock function with given fields: _a0, _a1, _a2
func (_m *SubscriptionServicer) ReceiveMessages(_a0 context.Context, _a1 *sync.WaitGroup, _a2 chan error) {
	_m.Called(_a0, _a1, _a2)
}
