// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pubsub "cloud.google.com/go/pubsub"
)

// SubscriptionCreator is an autogenerated mock type for the SubscriptionCreator type
type SubscriptionCreator struct {
	mock.Mock
}

// CreateSubscription provides a mock function with given fields: _a0, _a1, _a2
func (_m *SubscriptionCreator) CreateSubscription(_a0 context.Context, _a1 string, _a2 pubsub.SubscriptionConfig) (*pubsub.Subscription, error) {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 *pubsub.Subscription
	if rf, ok := ret.Get(0).(func(context.Context, string, pubsub.SubscriptionConfig) *pubsub.Subscription); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pubsub.Subscription)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string, pubsub.SubscriptionConfig) error); ok {
		r1 = rf(_a0, _a1, _a2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
