// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pubsub "cloud.google.com/go/pubsub"
)

// TopicCreator is an autogenerated mock type for the TopicCreator type
type TopicCreator struct {
	mock.Mock
}

// CreateTopic provides a mock function with given fields: _a0, _a1
func (_m *TopicCreator) CreateTopic(_a0 context.Context, _a1 string) (*pubsub.Topic, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *pubsub.Topic
	if rf, ok := ret.Get(0).(func(context.Context, string) *pubsub.Topic); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pubsub.Topic)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
