// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	pubsub "cloud.google.com/go/pubsub"
	mock "github.com/stretchr/testify/mock"
)

// TopicGetter is an autogenerated mock type for the TopicGetter type
type TopicGetter struct {
	mock.Mock
}

// Topic provides a mock function with given fields: id
func (_m *TopicGetter) Topic(id string) *pubsub.Topic {
	ret := _m.Called(id)

	var r0 *pubsub.Topic
	if rf, ok := ret.Get(0).(func(string) *pubsub.Topic); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pubsub.Topic)
		}
	}

	return r0
}
