{{- if .Values.secrets -}}
{{- range $secretName, $secretKeys := .Values.secrets }}
---
{{- if $secretKeys.apiVersion }}
apiVersion: {{ $secretKeys.apiVersion }}
{{- else }}
apiVersion: v1
{{- end }}
{{- if $secretKeys.kind }}
kind: {{ $secretKeys.kind }}
{{- else }}
kind: Secret
{{- end }}
metadata:
  name: {{ regexReplaceAll "_" $secretName "-" }}
  labels:
    {{- include "rcs.labels" $ | nindent 4 }}
    {{- if $secretKeys.labels }}
    {{- toYaml $secretKeys.labels | nindent 4 }}
    {{- end }}
  {{- if $secretKeys.annotations }}
  annotations:
    {{- toYaml $secretKeys.annotations | nindent 4 }}
  {{- end }}
{{- if $secretKeys.spec }}
spec:
  {{- toYaml $secretKeys.spec | nindent 2 }}
{{- end }}
{{- if or $secretKeys.data $secretKeys.generate }}
data:
  {{- with $secretKeys.data }}
  {{- range $key, $value := $secretKeys.data }}
  {{ $key }}: {{ ($value | b64enc) }}
  {{- end }}
  {{- end }}
  {{- if $secretKeys.generate }}
  {{- $secretObj := (lookup "v1" "Secret" $.Release.Namespace (regexReplaceAll "_" $secretName "-")) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $keyValue := "" }}
  {{- range $key, $value := $secretKeys.generate }}
    {{- if $value.useBinaryCharacters }}
      {{- $keyValue = (get $secretData $key) | default (randAscii ($value.length | int) | b64enc) }}
    {{- else }}
      {{- $keyValue = (get $secretData $key) | default (randAlphaNum ($value.length | int) | b64enc) }}
    {{- end }}
  {{ $key }}: {{ $keyValue | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
