{{- if .Values.secrets -}}
{{- range $secretName, $secretKeys := .Values.platform.secrets }}
---
{{- if $secretKeys.apiVersion }}
apiVersion: $secretKeys.apiVersion
{{- else }}
apiVersion: v1
{{- end }}
{{- if $secretKeys.kind }}
kind: $secretKeys.kind
{{- else }}
kind: Secret
{{- end }}
metadata:
  name: {{ regexReplaceAll "_" $secretName "-" }}
  labels:
    {{- include "identity-platform.labels" $ | nindent 4 }}
    {{- if $secretKeys.labels }}
    {{- toYaml $secretKeys.labels | nindent 4 }}
    {{- end }}
  {{- if $secretKeys.annotations }}
  annotations:
    {{- toYaml $secretKeys.annotations | nindent 4 }}
  {{- end }}
{{- if $secretKeys.spec }}
spec:
  {{- toYaml $secretKeys.spec | nindent 2 }}
{{- end }}
{{- if or $secretKeys.data $secretKeys.generate }}
data:
  {{- with $secretKeys.data }}
  {{- range $key, $value := $secretKeys.data }}
  {{ $key }}: {{ ($value | b64enc) }}
  {{- end }}
  {{- end }}
  {{- if $secretKeys.generate }}
  {{- $secretObj := (lookup "v1" "Secret" $.Release.Namespace (regexReplaceAll "_" $secretName "-")) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $keyValue := "" }}
  {{- range $key, $value := $secretKeys.generate }}
    {{- if $value.useBinaryCharacters }}
      {{- $keyValue = (get $secretData $key) | default (randAscii ($value.length | int)) }}
    {{- else }}
      {{- $keyValue = (get $secretData $key) | default (randAlphaNum ($value.length | int)) }}
    {{- end }}
  {{- if eq $secretName 'rcs_key' }}
    {{- if not get $secretData $key }}
    {{ print "###" }}
    {{ print "### Generating new password for server mode. Copy this password so you can enter it when configuring IDM." }}
    {{ printf "### Connect password: %s" $keyValue }}
    {{ print "###" }}
    {{- end }}
    {{- $keyValue = (get $secretData $key) | default sha1sum $keyValue | b64enc }}
  {{- end }}
  {{ $key }}: {{ $keyValue | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
