package idmapi

import (
	"github.com/ForgeCloud/saas/tree/master/services/go/common/pkg/models/user"
)

// Clienter interface for ForgeRock IDM API Client implementation.
type Clienter interface {
	// CreateTeamMember will create an TeamMember record with administrative priviledges.
	// The email, and password arguments are required. The ID generated by IDM is returned.
	CreateTeamMember(email string, password string, firstName string, lastName string) (id string, err error)

	// GetAppUser gets an AppUser by id
	GetAppUser(id string) (*user.User, error)

	// GetTeamMember gets a TeamMember by id
	GetTeamMember(id string) (*user.User, error)

	// UpdateTeamMember will update a TeamMember record with administrative priviledges.
	// The IDM Managed User id argument is required, but other string arguments will be ignored if they are blank.
	UpdateTeamMember(id string, email string, password string, firstName string, lastName string) error

	// DeleteTeamMember will delete a TeamMember record. The IDM Managed User id argument is required.
	DeleteTeamMember(id string) error
}
