{
 "title": "AM 6.0.0 CTS",
 "tags": [
  "AM",
  "6.0.0",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(am_cts_task_seconds,job)"
   },
   { "name": "aggregation_window", "label": "Aggregation Window", "query": "1m,5m,15m,1h,1d" },
   {
    "name": "token_type",
    "label": "Token Type",
    "query": "label_values(am_cts_task_seconds, token_type)"
   },
   {
    "name": "operation",
    "label": "Operation",
    "query": "label_values(am_cts_task_seconds, operation)"
   },
   {
    "name": "quantile",
    "label": "Percentile",
    "query": "label_values(am_cts_task_seconds, quantile)"
   },
   { "name": "outcome", "label": "Outcome", "query": "success,failure" }
  ]
 },
 "panels": [
  { "title": "CTS Cluster Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Tasks Throughput [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_cts_task_queue_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Total Tasks Waiting in Queues",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(am_cts_task_queue_size{job=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Overall Average Task Queueing Time [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate(am_cts_task_queue_seconds_total{job=~\"$instance\"}[$aggregation_window])) / sum (rate(am_cts_task_queue_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Overall Average Task Service Time [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate(am_cts_task_seconds_total{job=~\"$instance\"}[$aggregation_window])) / sum (rate(am_cts_task_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Task Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(am_cts_task_queue_count{job=~\"$instance\"}[90s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Tasks Waiting in Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "am_cts_task_queue_size{job=~\"$instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average Task Queueing Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(am_cts_task_queue_seconds_total{job=~\"$instance\"}[90s])) / sum by (job) (rate(am_cts_task_queue_count{job=~\"$instance\"}[90s]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average Task Service Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(am_cts_task_seconds_total{job=~\"$instance\"}[90s])) / sum by (job) (rate(am_cts_task_count{job=~\"$instance\"}[90s]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "$operation Tasks", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 }, "repeat": "operation" },
  {
   "title": "$operation Task Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(am_cts_task_count{job=~\"$instance\",token_type=~\"$token_type\",operation=~\"$operation\",outcome=~\"$outcome\"}[5m])",
     "legendFormat": "{{job}} {{token_type}} {{outcome}}"
    }
   ]
  },
  {
   "title": "$operation Task Service Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "am_cts_task_seconds{job=~\"$instance\",token_type=~\"$token_type\",operation=~\"$operation\",quantile=~\"$quantile\",outcome=~\"$outcome\"}",
     "legendFormat": "{{job}} {{token_type}} {{outcome}} p{{quantile}}"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Connections Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "am_cts_connection_count{job=~\"$instance\",outcome=~\"$outcome\"}",
     "legendFormat": "{{job}} {{outcome}}"
    }
   ]
  },
  {
   "title": "Connections Service Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "am_cts_connection_seconds{job=~\"$instance\",quantile=~\"$quantile\",outcome=~\"$outcome\"}",
     "legendFormat": "{{job}} {{outcome}} p{{quantile}}"
    }
   ]
  }
 ]
}