{
 "title": "IDM Sample Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": "label_values(job)" }
  ]
 },
 "panels": [
  { "title": "Self-Service Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Self-Service User Login Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "sum(idm_user_login_total)" }
   ]
  },
  {
   "title": "Self-Service Registration Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(idm_selfservice_user_registration_count)"
    }
   ]
  },
  {
   "title": "Self-Service Password Reset Total",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(idm_selfservice_user_password_reset_count)"
    }
   ]
  },
  {
   "title": "Login Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(idm_user_login_count[1m]))",
     "legendFormat": "m1_rate "
    },
    {
     "expr": "sum(rate(idm_user_login_count[5m]))",
     "legendFormat": "m5_rate"
    },
    {
     "expr": "sum(rate(idm_user_login_count[15m]))",
     "legendFormat": "m15_rate"
    }
   ]
  },
  {
   "title": "Registration Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(idm_selfservice_user_registration_count[1m]))",
     "legendFormat": "m1_rate "
    },
    {
     "expr": "sum(rate(idm_selfservice_user_registration_count[5m]))",
     "legendFormat": "m5_rate "
    },
    {
     "expr": "sum(rate(idm_selfservice_user_registration_count[15m]))",
     "legendFormat": "m15_rate "
    }
   ]
  },
  {
   "title": "User Password Rest Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(idm_selfservice_user_password_reset_count[1m])",
     "legendFormat": "m1_rate "
    },
    {
     "expr": "rate(idm_selfservice_user_password_reset_count[5m])",
     "legendFormat": "m5_rate "
    },
    {
     "expr": "rate(idm_selfservice_user_password_reset_count[15m])",
     "legendFormat": "m15_rate "
    }
   ]
  },
  { "title": "Managed Object Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Managed User Median",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "idm_managed_seconds{managed_object=\"user\",quantile=\"0.5\"}",
     "legendFormat": "{{operation}} "
    }
   ]
  },
  {
   "title": "Managed Role Median",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "idm_managed_seconds{managed_object=\"role\",quantile=\"0.5\"}",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Managed Object Average",
   "type": "graph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(idm_managed_seconds{managed_object=\"user\"}[1m]))",
     "legendFormat": "user m1_rate"
    },
    {
     "expr": "sum(rate(idm_managed_seconds{managed_object=\"user\"}[15m]))",
     "legendFormat": "user m15_rate"
    },
    {
     "expr": "sum(rate(idm_managed_seconds{managed_object=\"role\"}[1m]))",
     "legendFormat": "role m1_rate"
    },
    {
     "expr": "sum(rate(idm_managed_seconds{managed_object=\"role\"}[15m]))",
     "legendFormat": "role  m15_rate"
    }
   ]
  },
  { "title": "Sync Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Sync Object Mapping Median",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "idm_sync_objectmapping_seconds{quantile=\"0.5\"}",
     "legendFormat": "{{mapping_name}} "
    }
   ]
  },
  {
   "title": "Sync Average",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
   "yaxes": [
    { "format": "ops", "label": "calls/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(idm_sync_objectmapping_count[1m]))",
     "legendFormat": "sync m1_rate"
    },
    {
     "expr": "sum(rate(idm_sync_objectmapping_count[5m]))",
     "legendFormat": "sync m5_rate"
    },
    {
     "expr": "sum(rate(idm_sync_objectmapping_count[15m]))",
     "legendFormat": "sync m15_rate"
    }
   ]
  },
  { "title": "Recon Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 } },
  {
   "title": "Recon Average",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(idm_recon_seconds_total[1m])",
     "legendFormat": "m1_rate"
    },
    {
     "expr": "rate(idm_recon_seconds_total[5m])",
     "legendFormat": "m5_rate"
    },
    {
     "expr": "rate(idm_recon_seconds_total[15m])",
     "legendFormat": "m15_rate"
    }
   ]
  },
  { "title": "Repo Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Repo Median",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "sum(idm_repo_seconds{quantile=\"0.5\", operation=\"create\"})",
     "legendFormat": "create "
    },
    {
     "expr": "sum(idm_repo_seconds{quantile=\"0.5\", operation=\"read\"})",
     "legendFormat": "read"
    },
    {
     "expr": "sum(idm_repo_seconds{quantile=\"0.5\", operation=\"update\"})",
     "legendFormat": "update"
    },
    {
     "expr": "sum(idm_repo_seconds{quantile=\"0.5\", operation=\"delete\"})",
     "legendFormat": "delete"
    },
    {
     "expr": "sum(idm_repo_seconds{quantile=\"0.5\", operation=\"patch\"})",
     "legendFormat": "patch"
    },
    {
     "expr": "sum(idm_repo_seconds{quantile=\"0.5\", operation=\"action\"})",
     "legendFormat": "action"
    },
    {
     "expr": "sum(idm_repo_seconds{quantile=\"0.5\", operation=\"query\"})",
     "legendFormat": "query"
    }
   ]
  },
  {
   "title": "Repo Average",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(idm_repo_seconds{quantile=\"0.5\", operation=\"create\"}[5m]))",
     "legendFormat": "create m5_rate"
    },
    {
     "expr": "sum(rate(idm_repo_seconds{quantile=\"0.5\", operation=\"read\"}[5m]))",
     "legendFormat": "read m5_rate"
    },
    {
     "expr": "sum(rate(idm_repo_seconds{quantile=\"0.5\", operation=\"update\"}[5m]))",
     "legendFormat": "update m5_rate"
    },
    {
     "expr": "sum(rate(idm_repo_seconds{quantile=\"0.5\", operation=\"delete\"}[5m]))",
     "legendFormat": "delete m5_rate"
    },
    {
     "expr": "sum(rate(idm_repo_seconds{quantile=\"0.5\", operation=\"patch\"}[5m]))",
     "legendFormat": "patch m5_rate"
    },
    {
     "expr": "sum(rate(idm_repo_seconds{quantile=\"0.5\", operation=\"action\"}[5m]))",
     "legendFormat": "action m5_rate"
    },
    {
     "expr": "sum(rate(idm_repo_seconds{quantile=\"0.5\", operation=\"query\"}[5m]))",
     "legendFormat": "query m5_rate"
    }
   ]
  },
  { "title": "Audit Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "Audit Average",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "ops", "label": "events/sec" }
   ],
   "targets": [
    { "expr": "rate(idm_audit_count[5m])", "legendFormat": "{{audit_topic}} m5_rate" }
   ]
  }
 ]
}