/*
 * Copyright 2024 Ping Identity Corporation. All Rights Reserved
 * 
 * This code is to be used exclusively in connection with Ping Identity 
 * Corporation software or services. Ping Identity Corporation only offers
 * such software or services to legal entities who have entered into a 
 * binding license agreement with Ping Identity Corporation.
 */
//===============================================
// functional-tests-eks pipeline for ForgeOps
//===============================================

@Library([
    'forgerock-pipeline-libs@7d7b585639d060ade751c59e3cbf23e127d17063',
    'java-pipeline-libs@c7f1fb930553cac9e84d4af6ddc80fc4b10916d9'
]) _

def pipelineRun

node('gce-vm-forgeops-n2d-standard-8') {
    stage('Clone repo') {
        checkout scm

        def jobLocation = "${env.WORKSPACE}/jenkins-scripts/pipelines/build"
        def libsLocation = "${env.WORKSPACE}/jenkins-scripts/libs"
        def stagesLocation = "${env.WORKSPACE}/jenkins-scripts/stages"

        localGitUtils = load("${libsLocation}/git-utils.groovy")
        commonModule = load("${libsLocation}/common.groovy")

        currentBuild.displayName = "#${BUILD_NUMBER} - ${commonModule.SHORT_GIT_COMMIT}"
        currentBuild.description = 'built:'

        if (env.TAG_NAME) {
            currentBuild.result = 'ABORTED'
            error 'This pipeline does not currently support building from a tag'
        }
        functionalTests = load("${stagesLocation}/functional-tests-eks.groovy")
    }

    initialSteps()
    functionalTests.runStage()
    finalNotification()
}

def initialSteps() {
    properties([
            buildDiscarder(logRotator(numToKeepStr: '20', artifactNumToKeepStr: '20')),
            pipelineTriggers([cron('H 2 * * 1-5')]),
    ])

    slackChannel = '#forgeops-notify'
}

def finalNotification() {
    stage('Final notification') {
        // If some of the tests fail, the plugin that manages this doesn't throw an exception,
        // but it does set the build result to UNSTABLE/FAILURE. If it does not do that => SUCCESS
        if (!currentBuild.result || currentBuild.result == 'SUCCESS') {
            currentBuild.result = 'SUCCESS'

            // Send a 'build is back to normal' notification if the previous build was not good
            if (buildIsBackToNormal()) {
                slackUtils.sendBackToNormalMessage(slackChannel)
            } else {
                sendSlackNotification()
            }
        } else {
            sendSlackNotification()
        }
    }
}

private void sendSlackNotification(String messageSuffix = '') {
    slackUtils.sendStatusMessage(slackChannel, currentBuild.result, messageSuffix)
}
