// Code generated by mockery v1.0.0. DO NOT EDIT.
package httputil

import gojsonschema "github.com/xeipuuv/gojsonschema"
import http "net/http"
import mock "github.com/stretchr/testify/mock"

// MockEntitySchemaValidator is an autogenerated mock type for the EntitySchemaValidator type
type MockEntitySchemaValidator struct {
	mock.Mock
}

// Validate provides a mock function with given fields: request
func (_m *MockEntitySchemaValidator) Validate(request *http.Request) (*gojsonschema.Result, error) {
	ret := _m.Called(request)

	var r0 *gojsonschema.Result
	if rf, ok := ret.Get(0).(func(*http.Request) *gojsonschema.Result); ok {
		r0 = rf(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gojsonschema.Result)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(request)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
