// Code generated by mockery v1.0.0. DO NOT EDIT.
package httputil

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// MockHTTPClienter is an autogenerated mock type for the HTTPClienter type
type MockHTTPClienter struct {
	mock.Mock
}

// Do provides a mock function with given fields: req
func (_m *MockHTTPClienter) Do(req *http.Request) (*http.Response, error) {
	ret := _m.Called(req)

	var r0 *http.Response
	if rf, ok := ret.Get(0).(func(*http.Request) *http.Response); ok {
		r0 = rf(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*http.Response)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*http.Request) error); ok {
		r1 = rf(req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
