// Code generated by mockery v1.0.0. DO NOT EDIT.

package mailworker

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// MockSMTPMail is an autogenerated mock type for the MockSMTPMail type
type MockSMTPMail struct {
	mock.Mock
}

// IsActive provides a mock function with given fields:
func (_m *MockSMTPMail) IsActive() bool {
	ret := _m.Called()

	var r0 bool
	if rf, ok := ret.Get(0).(func() bool); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Send provides a mock function with given fields: m
func (_m *MockSMTPMail) Send(ctx context.Context, m MailMessage) error {
	ret := _m.Called(ctx, m)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, MailMessage) error); ok {
		r0 = rf(ctx, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendWithDelay provides a mock function with given fields: m, delayInSeconds
func (_m *MockSMTPMail) SendWithDelay(ctx context.Context, m MailMessage, delayInSeconds int) error {
	ret := _m.Called(ctx, m, delayInSeconds)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, MailMessage, int) error); ok {
		r0 = rf(ctx, m, delayInSeconds)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
