// Code generated by mockery v1.0.0. DO NOT EDIT.
package mailworker

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

// SendTemplate provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockSender) SendTemplate(_a0 context.Context, _a1 SendEmailMessage, _a2 int) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, SendEmailMessage, int) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
