# Extend Postgres to be used as an OpenIDM repository.
# See https://hub.docker.com/_/postgres/
#
# Copyright (c) 2016-2017 ForgeRock AS. Use of this source code is subject to the
# Common Development and Distribution License (CDDL) that can be found in the LICENSE file
#

FROM postgres:9.6.1

ADD sql/* /docker-entrypoint-initdb.d/


