{
 "title": "AM Overview",
 "tags": [
  "AM",
  "6.0.0",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(am_authentication_count, job)"
   },
   { "name": "aggregation_window", "label": "Aggregation Window", "query": "1m,5m,15m,1h,1d" }
  ]
 },
 "panels": [
  { "title": "Authentications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Started AuthN Throughput [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_session_count{job=~\"$instance\",session_type=~\"authentication-.*\",operation=\"create\",outcome=\"success\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Total Successful AuthN Throughput [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_authentication_count{job=~\"$instance\",outcome=\"success\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Total Failed AuthN Throughput [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_authentication_count{job=~\"$instance\",outcome=\"failure\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Total Timed-out AuthN Throughput [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_session_count{job=~\"$instance\",session_type=~\"authentication-.*\",operation=\"max-timeout\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Started AuthN Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(am_session_count{job=~\"$instance\",session_type=~\"authentication-.*\",operation=\"create\",outcome=\"success\"}[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Successful AuthN Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(am_authentication_count{job=~\"$instance\",outcome=\"success\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Failed AuthN Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(am_authentication_count{job=~\"$instance\",outcome=\"failure\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Timed-out AuthN Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(am_session_count{job=~\"$instance\",session_type=~\"authentication-.*\",operation=\"max-timeout\"}[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Sessions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total Session Creation Throughput [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_session_count{job=~\"$instance\",session_type!~\"authentication-client-based|authentication-cts-based|authentication-in-memory\",outcome=\"success\",operation=~\"create\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Total Session Termination Throughput [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 10 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_session_count{job=~\"$instance\",session_type!~\"authentication-client-based|authentication-cts-based|authentication-in-memory\",outcome=\"success\",operation=~\"logout|destroy|idle-timeout|max-timeout\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Overall Average Session Lifetime [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 10 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate(am_session_lifetime_seconds_total{job=~\"$instance\",session_type!~\"authentication-client-based|authentication-cts-based|authentication-in-memory\"}[$aggregation_window])) / sum (rate(am_session_lifetime_count{job=~\"$instance\",session_type!~\"authentication-client-based|authentication-cts-based|authentication-in-memory\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Session Creation Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(am_session_count{job=~\"$instance\",session_type!~\"authentication-client-based|authentication-cts-based|authentication-in-memory\",outcome=\"success\",operation=~\"create\"}[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Session Termination Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(am_session_count{job=~\"$instance\",session_type!~\"authentication-client-based|authentication-cts-based|authentication-in-memory\",outcome=\"success\",operation=~\"logout|destroy|idle-timeout|max-timeout\"}[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average Session Lifetime",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(am_session_lifetime_seconds_total{job=~\"$instance\",session_type!~\"authentication-client-based|authentication-cts-based|authentication-in-memory\"}[90s])) / sum by (job) (rate(am_session_lifetime_count{job=~\"$instance\",session_type!~\"authentication-client-based|authentication-cts-based|authentication-in-memory\"}[90s]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "CTS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total Task Throughput [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_cts_task_queue_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Total Tasks Waiting in Queues",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(am_cts_task_queue_size{job=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Overall Average Task Queueing Time [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 19 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate(am_cts_task_queue_seconds_total{job=~\"$instance\"}[$aggregation_window])) / sum (rate(am_cts_task_queue_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Overall Average Task Service Time [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 19 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate(am_cts_task_seconds_total{job=~\"$instance\"}[$aggregation_window])) / sum (rate(am_cts_task_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Task Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(am_cts_task_queue_count{job=~\"$instance\"}[90s])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Tasks Waiting in Queue",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "am_cts_task_queue_size{job=~\"$instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average Task Queueing Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(am_cts_task_queue_seconds_total{job=~\"$instance\"}[90s])) / sum by (job) (rate(am_cts_task_queue_count{job=~\"$instance\"}[90s]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average Task Service Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(am_cts_task_seconds_total{job=~\"$instance\"}[90s])) / sum by (job) (rate(am_cts_task_count{job=~\"$instance\"}[90s]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "OAuth2", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "OAuth2 Grants Throughput [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_oauth2_grant_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "OAuth2 Grant Revokes Throughput [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_oauth2_grant_revoke_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "OAuth2 Token Issuance Throughput [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_oauth2_token_issue_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "OAuth2 Token Revocation Throughput [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 28 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_oauth2_token_revoke_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "OAuth2 Grant Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(am_oauth2_grant_count{job=~\"$instance\"}[90s]) ",
     "legendFormat": "{{job}} - {{grant_type}}"
    }
   ]
  },
  {
   "title": "OAuth2 Grant Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(am_oauth2_grant_count{job=~\"$instance\"}[90s]) ",
     "legendFormat": "{{job}} - {{grant_type}}"
    }
   ]
  },
  {
   "title": "OAuth2 Token Issuance Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(am_oauth2_token_issue_count{job=~\"$instance\"}[90s]) ",
     "legendFormat": "{{job}} - {{token_type}}"
    }
   ]
  },
  {
   "title": "OAuth2 Token Revocation Throughput",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "irate(am_oauth2_token_revoke_count{job=~\"$instance\"}[90s]) ",
     "legendFormat": "{{job}} - {{token_type}}"
    }
   ]
  },
  { "title": "Policy / Authorization", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Total Policy Evaluation Throughput [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 37 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_authorization_policy_set_evaluate_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Overall Average Policy Evaluation Service Time [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 37 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate(am_authorization_policy_set_evaluate_seconds_total{job=~\"$instance\"}[$aggregation_window])) / sum (rate(am_authorization_policy_set_evaluate_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Policy Evaluation Outcomes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(irate(am_authorization_policy_set_evaluate_count{job=~\"$instance\"}[1m])) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average Policy Evaluation Service Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum by (job) (rate(am_authorization_policy_set_evaluate_seconds_total{job=~\"$instance\"}[90s])) / sum by (job) (rate(am_authorization_policy_set_evaluate_count{job=~\"$instance\"}[90s]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "JVM ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }, "repeat": "instance" },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "am_jvm_free_used_memory_bytes{job=~\"$instance\"}",
     "legendFormat": "{{job}} JVM Free Memory",
     "target": "*.ds.jvm-memory-usage.memory-usage.total.used"
    },
    {
     "expr": "am_jvm_used_memory_bytes{job=~\"$instance\"}",
     "legendFormat": "{{job}} JVM Used Memory",
     "target": "*.ds.jvm-memory-usage.memory-usage.total.used"
    },
    {
     "expr": "am_jvm_max_memory_bytes{job=~\"$instance\"}",
     "legendFormat": "{{job}} JVM Max Memory",
     "target": "*.ds.jvm-memory-usage.memory-usage.total.used"
    }
   ]
  },
  {
   "title": "Garbage Collections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(am_jvm_garbage_collector_ps_marksweep_count{job=~\"$instance\"}[1m])",
     "legendFormat": "{{job}} GC PS MarkSweep m1_rate",
     "target": "perSecond(*.ds.jvm-memory-usage.garbage-collector.*.count)"
    },
    {
     "expr": "rate(am_jvm_garbage_collector_ps_scavenge_count{job=~\"$instance\"}[1m])",
     "legendFormat": "{{job}} GC PS Scavenge m1_rate"
    }
   ]
  }
 ]
}