{
 "title": "IG sample",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "route", "query": "label_values(route)" }
  ]
 },
 "panels": [
  {
   "title": "Deployed Routes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 6, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ig_router_deployed_routes{heap=\"gateway\",name=\"_router\"}"
    }
   ]
  },
  { "title": "Route $route", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }, "repeat": "route" },
  {
   "title": "Requests / second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 17, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ig_route_request_total{router=\"gateway._router\", route=\"$route\"}[1m])",
     "legendFormat": "1 min"
    }
   ]
  },
  {
   "title": "Active requests",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 7 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "ig_route_request_active{route=\"$route\",router=\"gateway._router\"}"
    }
   ]
  },
  {
   "title": "Status family repartition",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (family) (irate(ig_route_response_status_total{route=\"$route\",router=\"gateway._router\"}[1m]))",
     "legendFormat": "{{family}}"
    }
   ]
  }
 ]
}