// Code generated by mockery v1.0.0. DO NOT EDIT.
package pubsubclient

import mock "github.com/stretchr/testify/mock"

// MockMessagerWithData is an autogenerated mock type for the MessagerWithData type
type MockMessagerWithData struct {
	mock.Mock
}

// Ack provides a mock function with given fields:
func (_m *MockMessagerWithData) Ack() {
	_m.Called()
}

// Data provides a mock function with given fields:
func (_m *MockMessagerWithData) Data() []byte {
	ret := _m.Called()

	var r0 []byte
	if rf, ok := ret.Get(0).(func() []byte); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	return r0
}

// Nack provides a mock function with given fields:
func (_m *MockMessagerWithData) Nack() {
	_m.Called()
}
