// Code generated by mockery v1.0.0. DO NOT EDIT.
package pubsubclient

import mock "github.com/stretchr/testify/mock"

// MockMessager is an autogenerated mock type for the Messager type
type MockMessager struct {
	mock.Mock
}

// Ack provides a mock function with given fields:
func (_m *MockMessager) Ack() {
	_m.Called()
}

// Nack provides a mock function with given fields:
func (_m *MockMessager) Nack() {
	_m.Called()
}
