// Code generated by mockery v1.0.0. DO NOT EDIT.
package mail

import context "context"
import mock "github.com/stretchr/testify/mock"

// MockSendMailServicer is an autogenerated mock type for the SendMailServicer type
type MockSendMailServicer struct {
	mock.Mock
}

// SendSendEmailTask provides a mock function with given fields: _a0, _a1
func (_m *MockSendMailServicer) SendSendEmailTask(_a0 context.Context, _a1 SendEmailMessage) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, SendEmailMessage) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
