{
 "title": "IG Performance",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "connection_remote",
    "label": "Connection remote",
    "query": {
     "query": "label_values(ig_http_client_active_connections,remote)"
    }
   },
   { "name": "time_interval", "label": "Time interval (min)", "query": "1m,5m,10m,30m,60m" },
   {
    "name": "ig_pod",
    "label": "IG Pod",
    "query": {
     "query": "label_values(ig_http_client_requests,pod)"
    }
   },
   {
    "name": "http_method",
    "label": "HTTP Method",
    "query": {
     "query": "label_values(ig_http_client_requests,method)"
    }
   },
   {
    "name": "request_remote",
    "label": "Request remote",
    "query": {
     "query": "label_values(ig_http_client_requests,remote)"
    }
   },
   {
    "name": "http_code",
    "label": "HTTP Code",
    "query": {
     "query": "label_values(ig_http_client_response_time_seconds,code)"
    }
   },
   {
    "name": "active_quantile",
    "label": "Active quantile",
    "query": {
     "query": "label_values(ig_http_client_response_time_seconds, quantile)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "IG in client role -- Connections and requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "[IG in client role] HTTP Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "ig_http_client_active_connections{pod=~\"$ig_pod\",remote=~\"$connection_remote\"}",
       "legendFormat": "Active connections to {{remote}}"
      },
      {
       "expr": "sum(ig_http_client_active_connections{pod=~\"$ig_pod\"})",
       "legendFormat": "All active connections"
      }
     ]
    },
    {
     "title": "[IG in client role] Active requests (waiting for response)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 1 },
     "targets": [
      {
       "expr": "ig_http_client_active_requests{pod=~\"$ig_pod\", remote=~\"$request_remote\", method=~\"$http_method\"}",
       "legendFormat": "{{method}} requests waiting for {{remote}} "
      }
     ]
    },
    {
     "title": "[IG in client role] Requests rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "rate(ig_http_client_requests{pod=~\"$ig_pod\", method=~\"$http_method\",remote=~\"$request_remote\"}[$time_interval])",
       "legendFormat": "{{time_interval}} rate of {{method}} requests sent to {{remote}} "
      }
     ]
    },
    {
     "title": "[IG in client role] Active web sockets",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 10 },
     "targets": [
      {
       "expr": "ig_http_client_active_ws_connections{pod=~\"$ig_pod\", remote=~\"$request_remote\"}",
       "legendFormat": "Active web sockets connection to {{remote}}"
      }
     ]
    },
    {
     "title": "[IG in client role] Mean response times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (method, remote, code) (ig_http_client_response_time_seconds{pod=~\"$ig_pod\", remote=~\"$request_remote\", method=~\"$http_method\", code=~\"$http_code\"})",
       "legendFormat": "Mean response time for {{method}} requests on {{remote}} which returned {{code}}"
      }
     ]
    },
    {
     "title": "[IG in client role] $time_interval rate for mean response times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (method, remote, code) (rate(ig_http_client_response_time_seconds{pod=~\"$ig_pod\", remote=~\"$request_remote\", method=~\"$http_method\", code=~\"$http_code\"}[$time_interval]))",
       "legendFormat": "{{method}} requests on {{remote}} which returned {{code}}"
      }
     ]
    },
    {
     "title": "[IG in client role] Quantile '${active_quantile}' response times",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 22, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ig_http_client_response_time_seconds{pod=~\"$ig_pod\", remote=~\"$request_remote\", method=~\"$http_method\", code=~\"$http_code\", quantile=~\"$active_quantile\"}",
       "legendFormat": "Quantile '{{quantile}}' response time for {{method}} requests on {{remote}} which returned {{code}}"
      }
     ]
    },
    {
     "title": "[IG in client role] Bytes read rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "irate(ig_http_client_bytes_read{pod=~\"$ig_pod\", remote=~\"$connection_remote\"}[$time_interval])",
       "legendFormat": "Bytes read from remote {{remote}}"
      }
     ]
    },
    {
     "title": "[IG in client role] Bytes written rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "irate(ig_http_client_bytes_written{pod=~\"$ig_pod\", remote=~\"$connection_remote\"}[$time_interval])",
       "legendFormat": "Bytes written to remote {{remote}}"
      }
     ]
    },
    {
     "title": "[IG in client role] Request bytes total rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "irate(ig_http_client_request_bytes_total{pod=~\"$ig_pod\", remote=~\"$request_remote\", method=~\"$http_method\"}[$time_interval])",
       "legendFormat": "{{method}} requests bytes total rate from remote {{remote}}"
      }
     ]
    },
    {
     "title": "[IG in client role] Response bytes total rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "irate(ig_http_client_response_bytes_total{pod=~\"$ig_pod\", remote=~\"$request_remote\", method=~\"$http_method\", code=~\"$http_code\"}[$time_interval])",
       "legendFormat": "Response bytes total rate for {{method}} requests to {{remote}} ended with {{code}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IG Timer metrics for total processing time in decorated filters (elapsed)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "$time_interval rate of time to process requests and responses in decorated filters and their downstream filters and handler",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ig_timerdecorator_filter_elapsed_seconds_total{pod=~\"$ig_pod\"}[$time_interval])",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "$time_interval rate count of requests and responses processed in decorated filters and their downstream filters and handler",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 2 },
     "targets": [
      {
       "expr": "rate(ig_timerdecorator_filter_elapsed_count{pod=~\"$ig_pod\"}[$time_interval])",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "Mean time to process requests and responses in decorated filters and its downstream filters and handler",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (pod, decorated_object) (ig_timerdecorator_filter_elapsed_seconds{pod=~\"$ig_pod\"})",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "$time_interval rate of mean time to process requests and responses in decorated filters and its downstream filters and handler",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (pod, decorated_object) (rate(ig_timerdecorator_filter_elapsed_seconds{pod=~\"$ig_pod\"}[$time_interval]))",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "$active_quantile quantile of time to process requests and responses in decorated filters and its downstream filters and handler",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ig_timerdecorator_filter_elapsed_seconds{pod=~\"$ig_pod\", quantile=~\"$active_quantile\"}",
       "legendFormat": "{{quantile}} for {{decorated_object}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IG Timer metrics for processing time in the decorated filters (internal)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "$time_interval rate of time to process requests and responses in decorated objects",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ig_timerdecorator_filter_internal_seconds_total{pod=~\"$ig_pod\"}[$time_interval])",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "$time_interval rate count of requests and responses  processed in decorated objects",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 57 },
     "targets": [
      {
       "expr": "rate(ig_timerdecorator_filter_internal_count{pod=~\"$ig_pod\"}[$time_interval])",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "Mean time to process requests and responses in decorated objects",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (pod, decorated_object) (ig_timerdecorator_filter_internal_seconds{pod=~\"$ig_pod\"})",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "$time_interval rate of mean time to process requests and responses in decorated objects",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (pod, decorated_object) (rate(ig_timerdecorator_filter_internal_seconds{pod=~\"$ig_pod\"}[$time_interval]))",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "$active_quantile quantile of time (sec) to process requests and responses in decorated objects",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ig_timerdecorator_filter_internal_seconds{pod=~\"$ig_pod\", quantile=~\"$active_quantile\"}",
       "legendFormat": "{{quantile}} for {{decorated_object}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IG Timer metrics for processing time in downstream elements of decorated filters (downstream)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "$time_interval rate of time to process requests and responses in filters and handlers that are downstream of decorated objects",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ig_timerdecorator_filter_downstream_seconds_total{pod=~\"$ig_pod\"}[$time_interval])",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "$time_interval rate count of requests and responses processed in filters and handlers that are downstream of decorated objects",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 58 },
     "targets": [
      {
       "expr": "rate(ig_timerdecorator_filter_downstream_count{pod=~\"$ig_pod\"}[$time_interval])",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "Mean time to process requests and responses in filters and handlers that are downstream of decorated objects",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (pod, decorated_object) (ig_timerdecorator_filter_downstream_seconds{pod=~\"$ig_pod\"})",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "$time_interval rate of mean time to process requests and responses in filters and handlers that are downstream of decorated objects",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (pod, decorated_object) (rate(ig_timerdecorator_filter_downstream_seconds{pod=~\"$ig_pod\"}[$time_interval]))",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "$active_quantile quantile of time to process requests and responses in filters and handlers that are downstream of decorated objects",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 22, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ig_timerdecorator_filter_downstream_seconds{pod=~\"$ig_pod\", quantile=~\"$active_quantile\"}",
       "legendFormat": "{{quantile}} quantile for {{decorated_object}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IG Timer metrics for decorated handler objects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "$time_interval rate of time to process requests and responses in decorated handlers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ig_timerdecorator_handler_elapsed_seconds_total{pod=~\"$ig_pod\"}[$time_interval])",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "$time_interval rate of the count of requests and responses in decorated handlers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 5 },
     "targets": [
      {
       "expr": "rate(ig_timerdecorator_handler_elapsed_count{pod=~\"$ig_pod\"}[$time_interval])",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "Mean time to process the request and response in the decorated handler",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (pod, decorated_object) (ig_timerdecorator_handler_elapsed_seconds{pod=~\"$ig_pod\"})",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "$time_interval rate of mean time to process the request and response in the decorated handler",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (pod, decorated_object) (rate(ig_timerdecorator_handler_elapsed_seconds{pod=~\"$ig_pod\"}[$time_interval]))",
       "legendFormat": "{{decorated_object}}"
      }
     ]
    },
    {
     "title": "$active_quantile quantile of time to process the request and response in the decorated handler",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 22, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ig_timerdecorator_handler_elapsed_seconds{pod=~\"$ig_pod\", quantile=~\"$active_quantile\"}",
       "legendFormat": "{{quantile}} for {{decorated_object}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IG Client Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "[IG in client role] Queue pending",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "ig_http_client_queue_pending{pod=~\"$ig_pod\",remote=~\"$request_remote\"}",
       "legendFormat": "Number of requests pending in queue for {{remote}}"
      }
     ]
    },
    {
     "title": "[IG in client role] Queue request count rate ",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 6 },
     "targets": [
      {
       "expr": "irate(ig_http_client_queue_time_count{pod=~\"$ig_pod\", remote=~\"$request_remote\"}[$time_interval])",
       "legendFormat": "Queue request count rate for remove {{remote}}"
      }
     ]
    },
    {
     "title": "[IG in client role] Average wait time in queue",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (remote) (ig_http_client_queue_time_seconds{pod=~\"$ig_pod\", remote=~\"$request_remote\"})",
       "legendFormat": "Average time (sec) for remote {{remote}}"
      }
     ]
    },
    {
     "title": "[IG in client role] $time_interval rate of meanwait time in queue",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (remote) (rate(ig_http_client_queue_time_seconds{pod=~\"$ig_pod\", remote=~\"$request_remote\"}[$time_interval]))",
       "legendFormat": "{{remote}}"
      }
     ]
    },
    {
     "title": "[IG in client role] Quantile '$active_quantile' wait time in queue",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ig_http_client_queue_time_seconds{pod=~\"$ig_pod\",remote=~\"$request_remote\", quantile=~\"$active_quantile\"}",
       "legendFormat": "Quantile '{{quantile}}' wait time for {{remote}}"
      }
     ]
    },
    {
     "title": "[IG in client role] Queue time rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(ig_http_client_queue_time_seconds_total{pod=~\"$ig_pod\", remote=~\"$request_remote\"}[$time_interval])",
       "legendFormat": "Queue time total (seconds) for remote {{remote}}"
      }
     ]
    }
   ]
  },
  {
   "title": "IG in server role -- Connections and requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "[IG in server role] HTTP Active Connections",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 209 },
     "targets": [
      {
       "expr": "ig_http_server_active_connections{pod=~\"$ig_pod\"}",
       "legendFormat": "Active connection from {{local}}"
      }
     ]
    },
    {
     "title": "[IG in server role] Errors",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 209 },
     "targets": [
      {
       "expr": "ig_http_server_errors{pod=~\"$ig_pod\"}",
       "legendFormat": "Error with class {{class}} during connection to {{local}} "
      }
     ]
    },
    {
     "title": "[IG in server role] Request being processed",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 218 },
     "targets": [
      {
       "expr": "ig_http_server_active_requests{pod=~\"$ig_pod\"}",
       "legendFormat": "Active requests from {{local}}"
      }
     ]
    },
    {
     "title": "[IG in server role] Requests processed rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 218 },
     "targets": [
      {
       "expr": "rate(ig_http_server_requests{pod=~\"$ig_pod\", method=~\"$http_method\", code=~\"$http_code\"}[$time_interval])",
       "legendFormat": "{{method}} requests rate from {{local}} with response code {{code}}"
      }
     ]
    },
    {
     "title": "[IG in server role] Mean response time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 227 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (method, code) (ig_http_server_response_time_seconds{pod=~\"$ig_pod\", method=~\"$http_method\", code=~\"$http_code\"})",
       "legendFormat": "Mean response time for {{method}} requests which returned {{code}}"
      }
     ]
    },
    {
     "title": "[IG in server role] $time_interval rate of mean response time",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 227 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "avg by (method, code) (rate(ig_http_server_response_time_seconds{pod=~\"$ig_pod\", method=~\"$http_method\", code=~\"$http_code\"}[$time_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "[IG in server role] Quantile '$active_quantile' response time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 22, "x": 0, "y": 236 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "ig_http_server_response_time_seconds{pod=~\"$ig_pod\", method=~\"$http_method\", code=~\"$http_code\", quantile=~\"$active_quantile\"}",
       "legendFormat": "Quantile '{{quantile}}' response time for {{method}} requests which returned {{code}}"
      }
     ]
    },
    {
     "title": "[IG in server role] Bytes read rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 246 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "irate(ig_http_server_bytes_read{pod=~\"$ig_pod\"}[$time_interval])",
       "legendFormat": "Bytes read from local {{local}}"
      }
     ]
    },
    {
     "title": "[IG in server role] Bytes written rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 246 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "irate(ig_http_server_bytes_written{pod=~\"$ig_pod\"}[$time_interval])",
       "legendFormat": "Bytes written for local {{local}}"
      }
     ]
    },
    {
     "title": "[IG in server role] Request bytes total rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 255 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "irate(ig_http_server_request_bytes_total{pod=~\"$ig_pod\", method=~\"$http_method\"}[$time_interval])",
       "legendFormat": "{{method}} requests bytes total rate from local {{local}}"
      }
     ]
    },
    {
     "title": "[IG in server role] Response bytes total rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 11, "y": 255 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "irate(ig_http_server_response_bytes_total{pod=~\"$ig_pod\", method=~\"$http_method\", code=~\"$http_code\"}[$time_interval])",
       "legendFormat": "{{method}} response bytes total rate for local {{local}} with code {{code}}"
      }
     ]
    }
   ]
  }
 ]
}