{
 "title": "AM 8.0.1 CTS Token Reaper",
 "tags": [
  "AM",
  "8.0.1",
  "Prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(am_cts_reaper_deletion_total,job)"
   },
   { "name": "aggregation_window", "label": "Aggregation Window", "query": "1m,5m,15m,1h,1d" },
   {
    "name": "quantile",
    "label": "Percentile",
    "query": "label_values(am_cts_reaper_search_seconds,quantile)"
   },
   { "name": "outcome", "label": "Outcome", "query": "success,failure" }
  ]
 },
 "panels": [
  { "title": "Expired Token Identification", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Reaper Cache Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "am_cts_reaper_cache_size",
     "legendFormat": "{{job}}",
     "target": "aliasByNode($host.$instance.cts.reaper.cache.size, 5)"
    }
   ]
  },
  {
   "title": "Total Searches [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_cts_reaper_search_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Overall Average Search Service Time [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate(am_cts_reaper_search_seconds_total{job=~\"$instance\"}[$aggregation_window])) / sum (rate(am_cts_reaper_search_count{job=~\"$instance\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Search Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "idelta(am_cts_reaper_search_count{job=~\"$instance\",outcome=~\"$outcome\"}[10m])",
     "legendFormat": "{{job}} {{outcome}}",
     "target": "aliasByNode(perSecond($host.$instance.cts.reaper.search.$outcome.count), 4)"
    }
   ]
  },
  {
   "title": "Search Service Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 3 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "am_cts_reaper_search_seconds{outcome=~\"$outcome\",quantile=~\"$quantile\"}",
     "legendFormat": "{{job}} {{outcome}} p{{quantile}}",
     "target": "aliasByNode($host.$instance.cts.reaper.search.$outcome.$timing, 5)"
    }
   ]
  },
  { "title": "Token Deletions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Total Cache-based Deletions [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_cts_reaper_deletion_total{reaper_type=~\"cache\",outcome=~\"$outcome\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Total Search-based Deletions [$aggregation_window]",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(increase(am_cts_reaper_deletion_total{reaper_type=~\"search\",outcome=~\"$outcome\"}[$aggregation_window]))"
    }
   ]
  },
  {
   "title": "Cache-based Deletion Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "p/sec" }
   ],
   "targets": [
    {
     "expr": "irate(am_cts_reaper_deletion_total{reaper_type=~\"cache\",outcome=~\"$outcome\"}[1m])",
     "legendFormat": "{{job}} {{token_type}} {{outcome}}",
     "target": "aliasByNode(perSecond($host.$instance.cts.reaper.cache.*.deletion.$outcome.count), 5)"
    }
   ]
  },
  {
   "title": "Search-based Deletion Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "p/sec" }
   ],
   "targets": [
    {
     "expr": "irate(am_cts_reaper_deletion_total{reaper_type=~\"search\",outcome=~\"$outcome\"}[1m])",
     "legendFormat": "{{job}} {{token_type}} {{outcome}}",
     "target": "aliasByNode(perSecond($host.$instance.cts.reaper.cache.*.deletion.$outcome.count), 5)"
    }
   ]
  }
 ]
}