{
 "title": "DS Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(ds_health_status_alive, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(ds_health_status_alive, service)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(ds_health_status_alive, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "Alive Instances",
   "type": "stat",
   "description": "The number of DS instances reporting as alive.\nThis calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ds_health_status_alive{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"})\n"
    }
   ]
  },
  {
   "title": "Healthy Instances",
   "type": "stat",
   "description": "The number of DS instances reporting as healthy.\nThis calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ds_health_status_healthy{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Degraded Indexes",
   "type": "stat",
   "description": "The number of degraded indexes across all DS backends.\nThis calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ds_backend_degraded_index_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Active Persistent-Searches",
   "type": "stat",
   "description": "Total number of active LDAP persistent searches.\nThis calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ds_connection_handlers_ldap_active_persistent_searches{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"})\n"
    }
   ]
  },
  { "title": "Request Handling", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Request Throughput",
   "type": "stat",
   "description": "Total number of LDAP & HTTP requests processed over the displayed time range.\nThis calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ds_connection_handlers_ldap_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range]))\n+\nsum(increase(ds_connection_handlers_ldap_requests_failure_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range]))\n+\nsum(increase(ds_connection_handlers_http_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range]))\n+\nsum(increase(ds_connection_handlers_http_requests_failure_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "description": "Total number of active LDAP & HTTP connections.\nThis calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ds_current_connections{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"})\n"
    }
   ]
  },
  {
   "title": "Requests Waiting in Queue",
   "type": "stat",
   "description": "Total number of work requests currently queued waiting to be processed per DS instance. This calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ds_work_queue_requests_in_queue{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"})"
    }
   ]
  },
  {
   "title": "Average Request Service Time",
   "type": "stat",
   "description": "The average time taken to process a request over the displayed time range.\nThis calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n  sum(increase(ds_connection_handlers_ldap_requests_seconds_total{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range])) +\n  sum(increase(ds_connection_handlers_ldap_requests_failure_seconds_total{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range])) +\n  sum(increase(ds_connection_handlers_http_requests_seconds_total{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range])) +\n  sum(increase(ds_connection_handlers_http_requests_failure_seconds_total{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range]))\n) / (\n  sum(increase(ds_connection_handlers_ldap_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range])) +\n  sum(increase(ds_connection_handlers_ldap_requests_failure_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range])) +\n  sum(increase(ds_connection_handlers_http_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range])) +\n  sum(increase(ds_connection_handlers_http_requests_failure_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range]))\n)"
    }
   ]
  },
  {
   "title": "Request Throughput",
   "type": "graph",
   "description": "Number of LDAP & HTTP requests processed over the displayed time range per pod.\nThis calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (\n  irate(ds_connection_handlers_ldap_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n) or\nsum by (pod) (\n  irate(ds_connection_handlers_http_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "graph",
   "description": "Number of active LDAP & HTTP connections per cluster.\nThis calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (\n  ds_connection_handlers_http_active_connections_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}\n) +\nsum by (pod) (\n  ds_connection_handlers_ldap_active_connections_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}\n)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Requests Waiting in Queues",
   "type": "graph",
   "description": "Number of work requests currently queued waiting to be processed per DS instance.\nThis calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (\n  ds_work_queue_requests_in_queue{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}\n)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Average Request Service Time",
   "type": "graph",
   "description": "The average time taken to process a request over the displayed time range. This calculation takes into account the dashboard filter selections for service and pod. Results are grouped by pod and outcome.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "(\n  sum by (pod) (\n    irate(ds_connection_handlers_ldap_requests_seconds_total{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n  ) +\n  sum by (pod) (\n    irate(ds_connection_handlers_http_requests_seconds_total{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n  )\n) / (\n  sum by (pod) (\n    irate(ds_connection_handlers_ldap_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n  ) +\n  sum by (pod) (\n    irate(ds_connection_handlers_http_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n  )\n)",
     "legendFormat": "{{pod}} success"
    },
    {
     "expr": "(\n  sum by (pod) (\n    irate(ds_connection_handlers_ldap_requests_failure_seconds_total{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n  ) +\n  sum by (pod) (\n    irate(ds_connection_handlers_http_requests_failure_seconds_total{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n  )\n) / (\n  sum by (pod) (\n    irate(ds_connection_handlers_ldap_requests_failure_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n  ) +\n  sum by (pod) (\n    irate(ds_connection_handlers_http_requests_failure_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n  )\n)",
     "legendFormat": "{{pod}} failure"
    }
   ]
  },
  { "title": "Request Throughput by Label", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Request Throughput by Instance",
   "type": "graph",
   "description": "Number of LDAP & HTTP requests processed over the displayed time range per cluster. This calculation takes into account the dashboard filter selections for service and pod. Results are grouped by pod.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (\n  irate(ds_connection_handlers_ldap_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n) or\nsum by (pod) (\n  irate(ds_connection_handlers_http_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n) or\nsum by (pod) (\n  irate(ds_connection_handlers_ldap_requests_failure_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n) or\nsum by (pod) (\n  irate(ds_connection_handlers_http_requests_failure_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Request Throughput by Protocol",
   "type": "graph",
   "description": "Number of LDAP & HTTP requests processed over the displayed time range per cluster. This calculation takes into account the dashboard filter selections for service and pod. Results are grouped by service and LDAP vs HTTP.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (\n  irate(ds_connection_handlers_ldap_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n) or\nsum by (service) (\n  irate(ds_connection_handlers_ldap_requests_failure_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n)\n",
     "legendFormat": "{{service}} LDAP"
    },
    {
     "expr": "sum by (service) (\n  irate(ds_connection_handlers_http_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n) or\nsum by (service) (\n  irate(ds_connection_handlers_http_requests_failure_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n)\n",
     "legendFormat": "{{service}} HTTP"
    }
   ]
  },
  {
   "title": "Request Throughput by Request Type",
   "type": "graph",
   "description": "Number of LDAP & HTTP requests processed over the displayed time range per cluster. This calculation takes into account the dashboard filter selections for service and pod. Results are grouped by service and request type.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (sevice,type) (\n  irate(ds_connection_handlers_ldap_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n) or\nsum by (service,type) (\n  irate(ds_connection_handlers_http_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n) or\nsum by (service,type) (\n  irate(ds_connection_handlers_ldap_requests_failure_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n) or\nsum by (service,type) (\n  irate(ds_connection_handlers_http_requests_failure_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n)\n",
     "legendFormat": "{{service}} {{type}}"
    }
   ]
  },
  {
   "title": "Request Throughput by Outcome",
   "type": "graph",
   "description": "Number of LDAP & HTTP requests processed over the displayed time range per cluster. This calculation takes into account the dashboard filter selections for service and pod. Results are grouped by pod and outcome.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum by (service) (\n  irate(ds_connection_handlers_ldap_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n) or\nsum by (service) (\n  irate(ds_connection_handlers_http_requests_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n)\n",
     "legendFormat": "{{service}} success"
    },
    {
     "expr": "sum by (service) (\n  irate(ds_connection_handlers_ldap_requests_failure_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n) or\nsum by (service) (\n  irate(ds_connection_handlers_http_requests_failure_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n)\n",
     "legendFormat": "{{service}} failure"
    }
   ]
  },
  { "title": "Replication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Max Replication Receive Delay",
   "type": "stat",
   "description": "Max local delay in receiving replicated operations over the displayed time range.  This calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    ds_replication_replica_remote_replicas_receive_delay_seconds{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Max Replication Replay Delay",
   "type": "stat",
   "description": "Max local delay in replaying replicated operations over the displayed time range. This calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    ds_replication_replica_remote_replicas_replay_delay_seconds{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Max Entries Awaiting Update",
   "type": "stat",
   "description": "Max number of entries for which an update operation has been received but not replayed.  This calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  max_over_time(\n    ds_replication_replica_entries_awaiting_updates_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range]\n  )\n)"
    }
   ]
  },
  {
   "title": "Replication Updates Replayed",
   "type": "stat",
   "description": "Number of replayed updates over the displayed time range.  This calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(ds_replication_replica_replayed_updates_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Replication Receive Delay",
   "type": "graph",
   "description": "Current local delay in receiving replicated operations.  This calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(\n    ds_replication_replica_remote_replicas_receive_delay_seconds{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m]\n)\n",
     "legendFormat": "{{domain_name}} DS({{remote_server_id}}) → DS({{server_id}})"
    }
   ]
  },
  {
   "title": "Replication Replay Delay",
   "type": "graph",
   "description": "Current local delay in replaying replicated operations.  This calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max_over_time(\n    ds_replication_replica_remote_replicas_replay_delay_seconds{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m]\n)\n",
     "legendFormat": "{{domain_name}} DS({{remote_server_id}}) → DS({{server_id}})"
    }
   ]
  },
  {
   "title": "Requests Waiting in Queues",
   "type": "graph",
   "description": "Number of work requests currently queued waiting to be processed per DS instance. This calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (pod) (\n  ds_work_queue_requests_in_queue{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}\n)\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Replication Updates Replayed",
   "type": "graph",
   "description": "Number of entries for which an update operation has been received but not replayed yet by this replica.  This calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(ds_replication_replica_replayed_updates_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])\n",
     "legendFormat": "{{pod}} {{domain_name}}"
    }
   ]
  },
  {
   "title": "Inbound Queue Max",
   "type": "stat",
   "description": "Max number of remote updates received from the replication server but not replayed for any DS instance over the displayed time range.  This calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  max_over_time(ds_replication_replica_updates_inbound_queue{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range])\n)"
    }
   ]
  },
  {
   "title": "Outbound Queue Max",
   "type": "stat",
   "description": "Max number of local updates that are waiting to be sent to the replication server for any DS instance over the displayed time range. This calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(\n  max_over_time(ds_replication_replica_updates_outbound_queue{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range])\n)"
    }
   ]
  },
  {
   "title": "Replication Conflicts Unresolved",
   "type": "stat",
   "description": "Number of replication conflicts unresolved over the displayed time range.  This calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(ds_replication_replica_replayed_updates_conflicts_unresolved{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range])\n)"
    }
   ]
  },
  {
   "title": "Replication Conflicts Resolved",
   "type": "stat",
   "description": "Number of replication conflicts resolved over the displayed time range. This calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  increase(ds_replication_replica_replayed_updates_conflicts_resolved{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[$__range])\n)"
    }
   ]
  },
  { "title": "Entry Counts & Disk Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Entry Count",
   "type": "graph",
   "description": "This calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "ds_backend_entry_count{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}",
     "legendFormat": "{{pod}} {{backend}} {{base_dn}}"
    }
   ]
  },
  {
   "title": "Disk Free Space",
   "type": "graph",
   "description": "Free space on each DS disk.  This calculation takes into account the dashboard filter selections for service and pod.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "max_over_time(ds_disk_free_space_bytes{namespace=~\"$namespace\",service=~\"$service\",pod=~\"$pod\"}[1m])",
     "legendFormat": " {{pod}} {{disk}}"
    }
   ]
  }
 ]
}