{{- if .Values.amster.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: amster-scripts
  labels:
    {{- include "identity-platform.labels" . | nindent 4 }}
binaryData:
{{- $dir := include "platform.filesDir" . }}
{{- range $path, $_ := .Files.Glob (printf "%s/amster/scripts/**" $dir) }}
  {{ $path | replace (printf "%s/amster/scripts/" $dir) "" | sha256sum }}: {{ $.Files.Get $path | b64enc }}
{{- end }}
{{- end }}
