{{- if .Values.idm.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: idm-import-pem-certs
  labels:
    {{- include "identity-platform.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob (printf "%s/idm/import-pem-certs.sh" (include "platform.filesDir" .))).AsConfig | nindent 2 }}
{{- end }}
