{{- if .Values.idm.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: idm
  labels:
    {{- include "identity-platform.labels" . | nindent 4 }}
    {{- with .Values.idm.podLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  IDM_ENVCONFIG_DIRS: /opt/openidm/resolver
  LOGGING_PROPERTIES: /var/run/openidm/logging/logback/logback.xml
  OPENIDM_ANONYMOUS_PASSWORD: anonymous
  OPENIDM_CLUSTER_REMOVE_OFFLINE_NODE_STATE: "true"
  OPENIDM_CONFIG_REPO_ENABLED: "false"
  PROJECT_HOME: /opt/openidm
  OPENIDM_ICF_RETRY_DELAYSECONDS: "10"
  OPENIDM_ICF_RETRY_MAXRETRIES: "12"
  OPENIDM_AUDIT_HANDLER_JSON_ENABLED: "false"
  OPENIDM_AUDIT_HANDLER_STDOUT_ENABLED: "true"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: idm-logback-xml
  labels:
    {{- include "identity-platform.labels" . | nindent 4 }}
    {{- with .Values.idm.podLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{ (.Files.Glob "files/idm/logback.xml").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: idm-logging-properties
  labels:
    {{- include "identity-platform.labels" . | nindent 4 }}
    {{- with .Values.idm.podLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{ (.Files.Glob "files/idm/logging.properties").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: idm-init-scripts
  labels:
    {{- include "identity-platform.labels" . | nindent 4 }}
    {{- with .Values.idm.podLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{ (.Files.Glob "files/idm/init-scripts/**.sh").AsConfig | nindent 2 }}
{{- end }}
