{{- if eq (include "keystore_create.enabled" .) "true" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: keystore-create
  labels:
    {{- include "identity-platform.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob (printf "%s/keystore/keystore-create.sh" (include "platform.filesDir" .))).AsConfig | nindent 2 }}
{{- end }}
