{{- if .Values.platform.ingress.tls.secret.create -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.platform.ingress.tls.secret.name }}
  labels:
    {{- include "identity-platform.labels" . | nindent 4 }}
type: Opaque
data:
  tls.crt: {{ .Values.platform.ingress.tls.secret.create.crt }}
  tls.key: {{ .Values.platform.ingress.tls.secret.create.key }}
{{- end }}
{{- if .Values.platform.secrets_enabled -}}
{{- range $secretName, $secretKeys := .Values.platform.secrets }}
---
{{- if $secretKeys.apiVersion }}
apiVersion: $secretKeys.apiVersion
{{- else }}
apiVersion: v1
{{- end }}
{{- if $secretKeys.kind }}
kind: $secretKeys.kind
{{- else }}
kind: Secret
{{- end }}
metadata:
  name: {{ regexReplaceAll "_" $secretName "-" }}
  labels:
    {{- include "identity-platform.labels" $ | nindent 4 }}
    {{- if $secretKeys.labels }}
    {{- toYaml $secretKeys.labels | nindent 4 }}
    {{- end }}
  {{- if $secretKeys.annotations }}
  annotations:
  {{- if $secretKeys.annotations.autogenerate }}
    {{- $annotationBase := "secret-generator.v1.mittwald.de" }}
    {{- range $key, $value := $secretKeys.annotations }}
    {{- if eq $key "autogenerate" }}
    {{ printf "%s/%s" $annotationBase $key }}: {{ join "," $value | quote }}
    {{ else }}
    {{ printf "%s/%s" $annotationBase $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
  {{- else }}
    {{- toYaml $secretKeys.annotations | nindent 4 }}
  {{- end }}
  {{- end }}
{{- if $secretKeys.spec }}
spec:
  {{- toYaml $secretKeys.spec | nindent 2 }}
{{- end }}
{{- if or $secretKeys.data $secretKeys.generate }}
data:
  {{- with $secretKeys.data }}
  {{- range $key, $value := $secretKeys.data }}
  {{ $key }}: {{ ($value | b64enc) }}
  {{- end }}
  {{- end }}
  {{- if $secretKeys.generate }}
  {{- $secretObj := (lookup "v1" "Secret" $.Release.Namespace (regexReplaceAll "_" $secretName "-")) | default dict }}
  {{- $secretData := (get $secretObj "data") | default dict }}
  {{- $keyValue := "" }}
  {{- range $key, $value := $secretKeys.generate }}
    {{- if $value.useBinaryCharacters }}
      {{- $keyValue = (get $secretData $key) | default (randAscii ($value.length | int) | b64enc) }}
    {{- else }}
      {{- $keyValue = (get $secretData $key) | default (randAlphaNum ($value.length | int) | b64enc) }}
    {{- end }}
  {{ $key }}: {{ $keyValue | quote }}
  {{- end }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
