// Code generated by mockery v1.0.0. DO NOT EDIT.

package am

import app "github.com/ForgeCloud/saas/tree/master/services/go/common/pkg/models/app"
import mock "github.com/stretchr/testify/mock"

// Servicer is an autogenerated mock type for the Servicer type
type MockServicer struct {
	mock.Mock
}

// GetOAuth2Client provides a mock function with given fields: id
func (_m *MockServicer) GetOAuth2Client(id string) (*app.OAuth2Client, error) {
	ret := _m.Called(id)

	var r0 *app.OAuth2Client
	if rf, ok := ret.Get(0).(func(string) *app.OAuth2Client); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*app.OAuth2Client)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
