---
# Source: identity-platform/templates/end-user-ui-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: end-user-ui-init-scripts
  labels:
    helm.sh/chart: identity-platform-1.0.0
    app.kubernetes.io/name: identity-platform
    app.kubernetes.io/part-of: identity-platform
    app.kubernetes.io/instance: identity-platform
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    app: end-user-ui
    app.kubernetes.io/component: end-user-ui
data:
  
  filesystem-init.sh: |
    #!/bin/sh
  
    echo "Setting up writeable volume."
    echo "Creating tmp"
    mkdir -p /writeable/tmp
    echo "Creating usr/share"
    mkdir -p /writeable/usr/share
    cp -rp /usr/share/nginx /writeable/usr/share
