platform:
  disable_secret_agent_config: false
  truststore:
    secret:
      enabled: true
idm:
  enabled: true
  image:
    repository: idm
    tag: ""
idm_custom:
  image:
    repository: "idm-custom"
    tag: ""
