---
platform:
  disable_secret_agent_config: true
  secrets_enabled: true
  secrets:
    am_env_secrets:
      generate:
        AM_AUTHENTICATION_SHARED_SECRET:
          length: 32
          useBinaryCharacters: true
        AM_ENCRYPTION_KEY:
          length: 24
        AM_OIDC_CLIENT_SUBJECT_IDENTIFIER_HASH_SALT:
          length: 20
        AM_PASSWORDS_AMADMIN_CLEAR:
          length: 24
        AM_SELFSERVICE_LEGACY_CONFIRMATION_EMAIL_LINK_SIGNING_KEY:
          length: 32
        AM_SESSION_STATELESS_ENCRYPTION_KEY:
          length: 32
          useBinaryCharacters: true
        AM_SESSION_STATELESS_SIGNING_KEY:
          length: 32
          useBinaryCharacters: true
    amster_env_secrets:
      generate:
        IDM_PROVISIONING_CLIENT_SECRET:
          length: 24
        IDM_RS_CLIENT_SECRET:
          length: 24
    ds_env_secrets:
      generate:
        AM_STORES_APPLICATION_PASSWORD:
          length: 32
        AM_STORES_CTS_PASSWORD:
          length: 32
        AM_STORES_USER_PASSWORD:
          length: 32
    ds_passwords:
      generate:
        dirmanager.pw:
          length: 32
      data:
        monitor.pw: "password"
    idm_env_secrets:
      generate:
        OPENIDM_ADMIN_PASSWORD:
          length: 24
    keystore_create:
      generate:
        KEYSTORE_PASSWORD:
          length: 24
ssh_keygen:
  enabled: true
