ARG GO_BUILD_BASE=3.0.1-alpine3.10
FROM gcr.io/fr-saas-registry/go-build-base:${GO_BUILD_BASE} AS builder

ARG COMPONENT=common
ARG GOPROXY

RUN apk add --no-cache ca-certificates dep~=0.5

# Copy external dependencies
COPY go.mod go.sum ./
RUN go mod download

# Copy source
COPY $COMPONENT $COMPONENT

WORKDIR ./$COMPONENT
