---
# Source: identity-platform/templates/am-init-scripts-configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: am-init-scripts
  labels:
    helm.sh/chart: identity-platform-1.0.0
    app.kubernetes.io/name: identity-platform
    app.kubernetes.io/part-of: identity-platform
    app.kubernetes.io/instance: identity-platform
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    app: am
    app.kubernetes.io/component: am
data:
  
  {}
