#!/bin/bash

applyYaml() {
  local yaml=$1

  echo "$yaml" | kubectl create -f -
}

ingress=traefik
[ "$1" = "--nginx" ] && ingress=nginx
[ "$1" = "--haproxy" ] && ingress=haproxy

nginx_controller=${nginx_controller:-traefik.io/ingress-controller}

sa_repo=oci://us-docker.pkg.dev/forgeops-public/charts/secret-agent
sa_namespace=secret-agent
sa_version="v1.2.12"
sa_installed=$(kubectl get crd secretagentconfigurations.secret-agent.secrets.forgerock.io 2>/dev/null)
if [ -n "$sa_installed" ]; then
    echo "Secret agent has already been installed."
else
    echo "Secret agent not found.  Installing..."
    kubectl create namespace $sa_namespace 2>/dev/null || true
    helm upgrade secret-agent $sa_repo \
        ${sa_version:+--version=$sa_version} \
        --namespace $sa_namespace --install --reset-values \
        \
        --set tolerations[0]."key"="kubernetes\.io/arch" \
        --set tolerations[0]."effect"="NoSchedule" \
        --set tolerations[0]."operator"="Exists"
fi

cm_repo=https://charts.jetstack.io
cm_namespace=cert-manager
cm_version=
cm_installed=$(kubectl get crd -l app=cert-manager 2>/dev/null)
if [ -n "$cm_installed" ]; then
    echo "Certificate manager has already been installed."
else
    echo "Certificate manager not found.  Installing..."
    kubectl create namespace $cm_namespace 2>/dev/null || true
    helm upgrade cert-manager cert-manager --repo $cm_repo \
        --namespace $cm_namespace --install --reset-values \
        ${cm_version:+--version=$cm_version} \
        --set installCRDs=true \
        --set global.leaderElection.namespace=$cm_namespace \
        \
        --set tolerations[0]."key"="kubernetes\.io/arch" \
        --set tolerations[0]."effect"="NoSchedule" \
        --set tolerations[0]."operator"="Exists" \
        --set cainjector.tolerations[0]."key"="kubernetes\.io/arch" \
        --set cainjector.tolerations[0]."effect"="NoSchedule" \
        --set cainjector.tolerations[0]."operator"="Exists" \
        --set startupapicheck.tolerations[0]."key"="kubernetes\.io/arch" \
        --set startupapicheck.tolerations[0]."effect"="NoSchedule" \
        --set startupapicheck.tolerations[0]."operator"="Exists" \
        --set webhook.tolerations[0]."key"="kubernetes\.io/arch" \
        --set webhook.tolerations[0]."effect"="NoSchedule" \
        --set webhook.tolerations[0]."operator"="Exists"
fi

if [ "$ingress" = "traefik" ]; then
    traefik_pretty="Traefik Proxy (Ingress/Gateway API)"
    traefik_repo=https://traefik.github.io/charts
    traefik_chart_name=traefik
    traefik_namespace=${TRAEFIK_NAMESPACE:-traefik}
    traefik_version=
    traefik_installed=$(kubectl get clusterroles -l app.kubernetes.io/name=traefik 2>/dev/null)
    if [ -n "$ING_VERSION" ] && [ "${ING_VERSION%%.*.*}" -lt 40 ] ; then
      nginx_compat_values="\
--set providers.kubernetesIngressNginx.enabled=true \
--set providers.kubernetesIngressNginx.ingressClassByName=true \
--set providers.kubernetesIngressNginx.publishService.enabled=true"
    fi
    ing_crd_cmd="helm show crds traefik --repo $traefik_repo| kubectl apply --server-side --force-conflicts -f - && \
      kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.5.1/standard-install.yaml"
    if [ -n "$traefik_installed" ]; then
        echo "$traefik_pretty has already been installed."
    else
        echo "$traefik_pretty not found.  Installing..."
        if [ -n "$ing_crd_cmd" ] ; then
          eval $ing_crd_cmd
        fi
        kubectl create namespace $traefik_namespace 2>/dev/null || true
        helm upgrade $traefik_chart_name $traefik_chart_name --repo $traefik_repo \
            --namespace $traefik_namespace --install --reset-values $nginx_compat_values \
            ${traefik_version:+--version $traefik_version} \
            --set providers.kubernetesIngressNGINX.enabled=true \
            --set providers.kubernetesIngressNGINX.ingressClassByName=true \
            --set providers.kubernetesIngressNGINX.publishService.enabled=true \
            --set deployment.replicas=2 \
            --set ingressClass.enabled=true \
            --set ingressRoute.dashboard.enabled=false \
            --set providers.kubernetesIngress.publishedService.enabled=true \
            --set providers.kubernetesGateway.enabled=true \
            --set gateway.enabled=false \
            --set tolerations[0].'key'='kubernetes\.io/arch' \
            --set tolerations[0].'effect'='NoSchedule' \
            --set tolerations[0].'operator'='Exists'
    fi

    ing_class=$(cat <<EOF
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/managed-by: forgeops-prereqs
    app.kubernetes.io/name: traefik
    app.kubernetes.io/part-of: traefik
spec:
  controller: $nginx_controller
EOF
)
    nginx_current_controller=$(kubectl get ingressclass nginx -o="jsonpath={.spec.controller}" 2>/dev/null || true)
    if [ -z "$nginx_current_controller" ]; then
      applyYaml "$ing_class"
    elif [ "$nginx_current_controller" != "$nginx_controller" ]; then
      kubectl delete ingressclass nginx && applyYaml "$ing_class"
    fi
elif [ "$ingress" = "nginx" ]; then
    nx_repo=https://kubernetes.github.io/ingress-nginx
    nx_namespace=ingress-nginx
    nx_version=
    nx_installed=$(kubectl get clusterroles -l app.kubernetes.io/name=ingress-nginx 2>/dev/null)
    if [ -n "$nx_installed" ]; then
        echo "NGINX Ingress has already been installed."
    else
        echo "NGINX Ingress not found.  Installing..."
        kubectl create namespace $nx_namespace 2>/dev/null || true
        helm upgrade ingress-nginx ingress-nginx --repo $nx_repo \
            --namespace $nx_namespace --install --reset-values \
            ${nx_version:+--version=$nx_version} \
            --set controller.kind=Deployment \
            --set controller.replicaCount=2 \
            --set controller.allowSnippetAnnotations=true \
            --set controller.service.type=LoadBalancer \
            --set controller.service.externalTrafficPolicy=Local \
            --set controller.service.omitClusterIP=true \
            --set controller.publishService.enabled=true \
            --set controller.stats.enabled=true \
            --set controller.stats.service.omitClusterIP=true \
            --set controller.tolerations[0]."key"="kubernetes\.io/arch" \
            --set controller.tolerations[0]."effect"="NoSchedule" \
            --set controller.tolerations[0]."operator"="Exists" \
            --set controller.admissionWebhooks.patch.tolerations[0]."key"="kubernetes\.io/arch" \
            --set controller.admissionWebhooks.patch.tolerations[0]."effect"="NoSchedule" \
            --set controller.admissionWebhooks.patch.tolerations[0]."operator"="Exists" \
            --set defaultBackend.tolerations[0]."key"="kubernetes\.io/arch" \
            --set defaultBackend.tolerations[0]."effect"="NoSchedule" \
            --set defaultBackend.tolerations[0]."operator"="Exists"
    fi
else
    hp_repo=https://haproxy-ingress.github.io/charts
    hp_namespace=haproxy-ingress
    hp_version=
    hp_installed=$(kubectl get clusterroles -l app.kubernetes.io/name=haproxy-ingress 2>/dev/null)
    if [ -n "$hp_installed" ]; then
        echo "HAProxy Ingress has already been installed."
    else
        echo "HAProxy Ingress not found.  Installing..."
        kubectl create namespace $hp_namespace 2>/dev/null || true
        helm upgrade haproxy-ingress haproxy-ingress --repo $hp_repo \
            --namespace $hp_namespace --install --reset-values \
            ${hp_version:+--version=$hp_version} \
            --set controller.kind=Deployment \
            --set controller.replicaCount=2 \
            --set controller.minAvailable=2 \
            --set controller.service.type=LoadBalancer \
            --set controller.service.externalTrafficPolicy=Local \
            --set controller.publishService.enabled=true \
            --set controller.stats.enabled=true \
            --set controller.ingressClassResource.enabled=true \
            --set controller.tolerations[0]."key"="kubernetes\.io/arch" \
            --set controller.tolerations[0]."effect"="NoSchedule" \
            --set controller.tolerations[0]."operator"="Exists" \
            --set defaultBackend.tolerations[0]."key"="kubernetes\.io/arch" \
            --set defaultBackend.tolerations[0]."effect"="NoSchedule" \
            --set defaultBackend.tolerations[0]."operator"="Exists"
    fi
fi

