FROM forgerock-docker-public.bintray.io/forgerock/am:7.0.0-SNAPSHOT

# This is where you would copy in custom web.xml, add jar files, javascript, etc.
# The AM war is expanded to /usr/local/tomcat/webapps/am

# COPY web.xml /usr/local/tomcat/webapps/am/WEB-INF