// Code generated by mockery v1.0.0. DO NOT EDIT.
package messaging

import mock "github.com/stretchr/testify/mock"

// MockFailureStrategy is an autogenerated mock type for the FailureStrategy type
type MockFailureStrategy struct {
	mock.Mock
}

// ValidateForSubscriptionConfig provides a mock function with given fields: cfg
func (_m *MockFailureStrategy) ValidateForSubscriptionConfig(cfg SubscriptionServiceConfig) error {
	ret := _m.Called(cfg)

	var r0 error
	if rf, ok := ret.Get(0).(func(SubscriptionServiceConfig) error); ok {
		r0 = rf(cfg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// WrapHandler provides a mock function with given fields: h, trackingAttributes
func (_m *MockFailureStrategy) WrapHandler(h WrappedMessageHandlerFunc, trackingAttributes map[AttrKey]string) MessageHandlerFunc {
	ret := _m.Called(h, trackingAttributes)

	var r0 MessageHandlerFunc
	if rf, ok := ret.Get(0).(func(WrappedMessageHandlerFunc, map[AttrKey]string) MessageHandlerFunc); ok {
		r0 = rf(h, trackingAttributes)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(MessageHandlerFunc)
		}
	}

	return r0
}
