name: Helm Chart Validation

on:
  pull_request:
    paths:
      - 'charts/**'

jobs:
  helm-validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Validate Helm charts
        run: bash bin/check-helm.sh
