name: Publish RCS Chart
on:
  workflow_dispatch:

env:
  REGISTRY: "us-docker.pkg.dev"
jobs:
  build:
    if: github.repository == 'ForgeRock/forgeops'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Set tag
        id: set_tag
        run: |
          RELEASE_TAG=$(head -n 1 charts/rcs/README.md | awk -F= '{print $2}')
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Update helm chart versions
        id: update_helm_chart_versions
        run: |
          sed -i -e "s/^version:.*/version:\ ${{ env.RELEASE_TAG }}/" charts/rcs/Chart.yaml

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          charts_dir: charts
          pages_branch: gh-pages
          skip_existing: true
